--Select * from LIMSMaster

SELECT OrderID,
Accession [Sample ID],
PaymentMethod,
Barcode,
Specimen,
Collector,
OrderStatus,
BillingStatus,
SampleStatus,
RequestSubmittedDate,
RequestCollectDate,
ReqReceivedDate,
ReqReportedDate,
RessultedStatus [Resulted / Not],
ClientStatus,
TimeToResult [Time to Result (Resulted - Received)],
[Performing Laboratory],
Results,
PatientFirstName [Patient First Name],
PatientLastname [Patient Last Name],
PatientDateOfBirth [Patient Date of Birth],
VisitNumber,
AMDDOE [AMD DOE],
AMDLBD [AMD LBD],
TimetoBill [Time to Bill],
ClaimStatus,
BilledorNot [Billed/Not],
Facility,
Provider,
PrimaryInsurance [Primary Insurance],
PrimaryInsuranceID [Primary Insurance ID #],
ICD10Codes [ICD-10 Codes],
Tests,
PanelCategory
FROM LIMSMaster
