ALTER TABLE LIMSMaster ADD EntryStatus NVARCHAR(255)
ALTER TABLE LIMSMaster ADD PrimaryPolicyInformation NVARCHAR(255)
ALTER TABLE LIMSMaster ADD PrimaryInsurance NVARCHAR(255)
ALTER TABLE LIMSMaster ADD OrderInfo NVARCHAR(MAX)
ALTER TABLE LIMSMaster ADD DateOfBirth DATE
ALTER TABLE LIMSMaster ADD SalesRepEmail NVARCHAR(255)
ALTER TABLE LIMSMaster ADD ProviderLastName NVARCHAR(255)
ALTER TABLE LIMSMaster ADD ProviderFirstName NVARCHAR(255)
ALTER TABLE LIMSMaster ADD PatientFirstName NVARCHAR(255)
ALTER TABLE LIMSMaster ADD PatientLastName NVARCHAR(255)








