-- =====================================================================
-- NorthWest — Collection Summary Aggregates
-- Pre-computes the data behind the 13 Collection Summary tabs in the
-- LabMetricsDashboard web app.  Generated by _GenerateCollectionSummary.ps1.
-- All SPs are idempotent (TRUNCATE + INSERT) and safe to re-run.
--
-- Per-lab settings:
--   Panel column        = PanelType
--   Has BilledUnbilled  = False
--   Has AgingBucket     = False
-- =====================================================================

SET NOCOUNT ON;
GO

-- ?????????????????????????????????????????????????????????????????????
-- TABLE DEFINITIONS
-- ?????????????????????????????????????????????????????????????????????

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_Top5ReimbursementPct')
CREATE TABLE dbo.NW_CS_Top5ReimbursementPct
(
    SummaryId           INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PayerRank           TINYINT         NOT NULL,
    PayerName           NVARCHAR(500)   NOT NULL,
    SumInsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    SumChargeAmount     DECIMAL(18,2)   NOT NULL DEFAULT 0,
    UniqueVisitCount    INT             NOT NULL DEFAULT 0,
    PaymentPct          DECIMAL(9,4)    NOT NULL DEFAULT 0,
    RefreshedAt         DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_Top5ReimbursementPay')
CREATE TABLE dbo.NW_CS_Top5ReimbursementPay
(
    SummaryId         INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PayerRank         TINYINT         NOT NULL,
    PayerName         NVARCHAR(500)   NOT NULL,
    TotalPayments     DECIMAL(18,2)   NOT NULL DEFAULT 0,
    UniqueVisitCount  INT             NOT NULL DEFAULT 0,
    RefreshedAt       DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_MonthlyClaimVolume')
CREATE TABLE dbo.NW_CS_MonthlyClaimVolume
(
    SummaryId         INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PanelName         NVARCHAR(500)   NOT NULL,
    PayerName         NVARCHAR(500)   NOT NULL,
    PayerRank         TINYINT         NOT NULL,
    BillYear          INT             NOT NULL,
    BillMonth         TINYINT         NOT NULL,
    NoOfClaims        INT             NOT NULL DEFAULT 0,
    InsurancePayment  DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt       DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_WeeklyClaimVolume')
CREATE TABLE dbo.NW_CS_WeeklyClaimVolume
(
    SummaryId         INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PanelName         NVARCHAR(500)   NOT NULL,
    PayerName         NVARCHAR(500)   NOT NULL,
    PayerRank         TINYINT         NOT NULL,
    WeekKey           TINYINT         NOT NULL,
    WeekStart         DATE            NOT NULL,
    WeekEnd           DATE            NOT NULL,
    NoOfClaims        INT             NOT NULL DEFAULT 0,
    InsurancePayment  DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt       DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

DROP TABLE IF EXISTS dbo.NW_CS_PanelAverages;
GO
CREATE TABLE dbo.NW_CS_PanelAverages
(
    SummaryId           INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PanelName           NVARCHAR(500)   NOT NULL,
    PayerName           NVARCHAR(500)   NOT NULL,
    NoOfClaims          INT             NOT NULL DEFAULT 0,
    TotalCharges        DECIMAL(18,2)   NOT NULL DEFAULT 0,
    CarrierPayment      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgCarrierPayment   DECIMAL(18,2)   NOT NULL DEFAULT 0,
    FullyPaidCount      INT             NOT NULL DEFAULT 0,
    FullyPaidAmount     DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgFullyPaid        DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AdjudicatedCount    INT             NOT NULL DEFAULT 0,
    AdjudicatedAmount   DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgAdjudicated      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    Days30Count         INT             NOT NULL DEFAULT 0,
    Days30Amount        DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgDays30           DECIMAL(18,2)   NOT NULL DEFAULT 0,
    Days60Count         INT             NOT NULL DEFAULT 0,
    Days60Amount        DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgDays60           DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt         DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_AvgPayments')
CREATE TABLE dbo.NW_CS_AvgPayments
(
    SummaryId         INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PanelName         NVARCHAR(500)   NOT NULL,
    PayerName         NVARCHAR(500)   NOT NULL,
    PayerRank         TINYINT         NOT NULL,
    ClaimCount        INT             NOT NULL DEFAULT 0,
    TotalCharges      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgCharges        DECIMAL(18,2)   NOT NULL DEFAULT 0,
    InsurancePayment  DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgInsurancePayment DECIMAL(18,2) NOT NULL DEFAULT 0,
    FullyPaidCount    INT             NOT NULL DEFAULT 0,
    FullyPaidAmount   DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgFullyPaid      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AdjudicatedCount  INT             NOT NULL DEFAULT 0,
    AdjudicatedAmount DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgAdjudicated    DECIMAL(18,2)   NOT NULL DEFAULT 0,
    Over30Count       INT             NOT NULL DEFAULT 0,
    Over30Amount      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgOver30         DECIMAL(18,2)   NOT NULL DEFAULT 0,
    Over60Count       INT             NOT NULL DEFAULT 0,
    Over60Amount      DECIMAL(18,2)   NOT NULL DEFAULT 0,
    AvgOver60         DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt       DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_InsuranceVsAging')
CREATE TABLE dbo.NW_CS_InsuranceVsAging
(
    SummaryId        INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PayerName        NVARCHAR(500)   NOT NULL,
    AgingBucket      NVARCHAR(200)   NOT NULL,
    VisitCount       INT             NOT NULL DEFAULT 0,
    InsuranceBalance DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF OBJECT_ID('dbo.NW_CS_PanelVsPayment','U') IS NOT NULL DROP TABLE dbo.NW_CS_PanelVsPayment;
CREATE TABLE dbo.NW_CS_PanelVsPayment
(
    SummaryId        INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PanelName        NVARCHAR(500)   NOT NULL,
    PayerName        NVARCHAR(500)   NOT NULL,
    BillYear         INT             NOT NULL,
    BillMonth        TINYINT         NOT NULL,
    NoOfClaims       INT             NOT NULL DEFAULT 0,
    InsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_RepVsPayment')
CREATE TABLE dbo.NW_CS_RepVsPayment
(
    SummaryId        INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    SalesRepName     NVARCHAR(500)   NOT NULL,
    CheckYear        INT             NOT NULL,
    CheckMonth       TINYINT         NOT NULL,
    NoOfClaims       INT             NOT NULL DEFAULT 0,
    InsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_InsuranceVsPaymentPct')
CREATE TABLE dbo.NW_CS_InsuranceVsPaymentPct
(
    SummaryId        INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PayerName        NVARCHAR(500)   NOT NULL,
    NoOfPaidClaims   INT             NOT NULL DEFAULT 0,
    InsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PaymentPct       DECIMAL(9,4)    NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_CptVsPaymentPct')
CREATE TABLE dbo.NW_CS_CptVsPaymentPct
(
    SummaryId            INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CPTCode              NVARCHAR(50)    NOT NULL,
    SumUnits             DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PaidInsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PaidChargeAmount     DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PaymentPct           DECIMAL(9,4)    NOT NULL DEFAULT 0,
    RefreshedAt          DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

DROP TABLE IF EXISTS dbo.NW_CS_StatusSummary;
GO
CREATE TABLE dbo.NW_CS_StatusSummary
(
    SummaryId        INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ClaimStatus      NVARCHAR(200)   NOT NULL,
    PanelName        NVARCHAR(500)   NOT NULL,
    CptCode          NVARCHAR(MAX)   NOT NULL,   -- CPTCodeXUnitsXModifier can be a long concatenated list
    PayerName        NVARCHAR(500)   NOT NULL,
    NoOfClaims       INT             NOT NULL DEFAULT 0,
    InsurancePayment DECIMAL(18,2)   NOT NULL DEFAULT 0,
    InsuranceBalance DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PatientBalance   DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

IF OBJECT_ID('dbo.NW_CS_ProviderSummary','U') IS NOT NULL DROP TABLE dbo.NW_CS_ProviderSummary;
CREATE TABLE dbo.NW_CS_ProviderSummary
(
    SummaryId         INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ProviderRank      INT             NOT NULL,
    ReferringProvider NVARCHAR(500)   NOT NULL,
    NoOfClaims        INT             NOT NULL DEFAULT 0,
    ProcTotalPayment  DECIMAL(18,2)   NOT NULL DEFAULT 0,
    InsuranceBalance  DECIMAL(18,2)   NOT NULL DEFAULT 0,
    PatientBalance    DECIMAL(18,2)   NOT NULL DEFAULT 0,
    RefreshedAt       DATETIME        NOT NULL DEFAULT GETDATE()
);
GO


-- =====================================================================
-- STORED PROCEDURES
-- =====================================================================

-- 1. Top 5 Insurances | Reimbursement % (vs Billed Charge)

CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_Top5ReimbursementPct
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH agg AS (
        SELECT
            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS SumIns,
            ISNULL(SUM(TRY_CAST(ChargeAmount     AS DECIMAL(18,2))),0) AS SumChg,
            COUNT(NULLIF(LTRIM(RTRIM(AccessionNumber)), '')) AS Visits
        FROM dbo.ClaimLevelData
		Where
        -- PayerName_Raw IS NOT NULL
        --  AND LTRIM(RTRIM(PayerName_Raw)) <> '' AND
           ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
        GROUP BY LTRIM(RTRIM(PayerName_Raw))
    ),
    grand AS (SELECT NULLIF(SUM(SumIns), 0) AS GrandTotal FROM agg),
    ranked AS (
        SELECT TOP 5
               ROW_NUMBER() OVER (ORDER BY a.SumIns DESC) AS Rnk,
               a.PayerName, a.SumIns, a.SumChg, a.Visits,
              -- CAST(a.SumIns * 100.0 / ISNULL(g.GrandTotal, 1) AS DECIMAL(9,4)) AS PayPct
              CAST(a.SumIns * 100.0 / NULLIF(a.SumChg, 0) AS DECIMAL(9,4)) AS PayPct
        FROM agg a CROSS JOIN grand g
        ORDER BY a.SumIns DESC
    )
    SELECT * INTO #out FROM ranked;

    TRUNCATE TABLE dbo.NW_CS_Top5ReimbursementPct;
    INSERT INTO dbo.NW_CS_Top5ReimbursementPct
        (PayerRank, PayerName, SumInsurancePayment, SumChargeAmount, UniqueVisitCount, PaymentPct, RefreshedAt)
    SELECT CAST(Rnk AS TINYINT), PayerName, SumIns, SumChg, Visits, PayPct, GETDATE()
    FROM #out
    ORDER BY Rnk;

    DROP TABLE IF EXISTS #out;
    PRINT 'usp_RefreshNW_CS_Top5ReimbursementPct completed.';
END

--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_Top5ReimbursementPct
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH agg AS (
--        SELECT
--            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
--            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS SumIns,
--            ISNULL(SUM(TRY_CAST(ChargeAmount     AS DECIMAL(18,2))),0) AS SumChg,
--            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(AccessionNumber)), '')) AS Visits
--        FROM dbo.ClaimLevelData
--		Where
--        -- PayerName_Raw IS NOT NULL
--        --  AND LTRIM(RTRIM(PayerName_Raw)) <> '' AND
--           ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--        GROUP BY LTRIM(RTRIM(PayerName_Raw))
--    ),
--    grand AS (SELECT NULLIF(SUM(SumIns), 0) AS GrandTotal FROM agg),
--    ranked AS (
--        SELECT TOP 5
--               ROW_NUMBER() OVER (ORDER BY a.SumIns DESC) AS Rnk,
--               a.PayerName, a.SumIns, a.SumChg, a.Visits,
--               CAST(a.SumIns * 100.0 / ISNULL(g.GrandTotal, 1) AS DECIMAL(9,4)) AS PayPct
--        FROM agg a CROSS JOIN grand g
--        ORDER BY a.SumIns DESC
--    )
--    SELECT * INTO #out FROM ranked;

--    TRUNCATE TABLE dbo.NW_CS_Top5ReimbursementPct;
--    INSERT INTO dbo.NW_CS_Top5ReimbursementPct
--        (PayerRank, PayerName, SumInsurancePayment, SumChargeAmount, UniqueVisitCount, PaymentPct, RefreshedAt)
--    SELECT CAST(Rnk AS TINYINT), PayerName, SumIns, SumChg, Visits, PayPct, GETDATE()
--    FROM #out
--    ORDER BY Rnk;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_Top5ReimbursementPct completed.';
--END
GO


CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_Top5ReimbursementPay
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH agg AS (
        SELECT
            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS TotalPay,
            COUNT(NULLIF(LTRIM(RTRIM(AccessionNumber)), '')) AS Visits
        FROM dbo.ClaimLevelData
        WHERE
		--PayerName_Raw IS NOT NULL AND LTRIM(RTRIM(PayerName_Raw)) <> '' AND
           ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
        GROUP BY LTRIM(RTRIM(PayerName_Raw))
    ),
    ranked AS (
        SELECT TOP 5 PayerName, TotalPay, Visits,
               ROW_NUMBER() OVER (ORDER BY TotalPay DESC) AS Rnk
        FROM agg
        ORDER BY TotalPay DESC
    )
    SELECT * INTO #out FROM ranked;

    TRUNCATE TABLE dbo.NW_CS_Top5ReimbursementPay;
    INSERT INTO dbo.NW_CS_Top5ReimbursementPay
        (PayerRank, PayerName, TotalPayments, UniqueVisitCount, RefreshedAt)
    SELECT CAST(Rnk AS TINYINT), PayerName, TotalPay, Visits, GETDATE()
    FROM #out
    ORDER BY Rnk;

    DROP TABLE IF EXISTS #out;
    PRINT 'usp_RefreshNW_CS_Top5ReimbursementPay completed.';
END
--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_Top5ReimbursementPct
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH agg AS (
--        SELECT
--            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
--            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS SumIns,
--            ISNULL(SUM(TRY_CAST(ChargeAmount     AS DECIMAL(18,2))),0) AS SumChg,
--            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(AccessionNumber)), '')) AS Visits
--        FROM dbo.ClaimLevelData
--        WHERE PayerName_Raw IS NOT NULL
--          AND LTRIM(RTRIM(PayerName_Raw)) <> ''
--          AND ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--        GROUP BY LTRIM(RTRIM(PayerName_Raw))
--    ),
--    grand AS (SELECT NULLIF(SUM(SumIns), 0) AS GrandTotal FROM agg),
--    ranked AS (
--        SELECT TOP 5
--               ROW_NUMBER() OVER (ORDER BY a.SumIns DESC) AS Rnk,
--               a.PayerName, a.SumIns, a.SumChg, a.Visits,
--               CAST(a.SumIns * 100.0 / ISNULL(g.GrandTotal, 1) AS DECIMAL(9,4)) AS PayPct
--        FROM agg a CROSS JOIN grand g
--        ORDER BY a.SumIns DESC
--    )
--    SELECT * INTO #out FROM ranked;

--    TRUNCATE TABLE dbo.NW_CS_Top5ReimbursementPct;
--    INSERT INTO dbo.NW_CS_Top5ReimbursementPct
--        (PayerRank, PayerName, SumInsurancePayment, SumChargeAmount, UniqueVisitCount, PaymentPct, RefreshedAt)
--    SELECT CAST(Rnk AS TINYINT), PayerName, SumIns, SumChg, Visits, PayPct, GETDATE()
--    FROM #out
--    ORDER BY Rnk;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_Top5ReimbursementPct completed.';
--END
--GO


-- 2. Top 5 Insurances | Reimbursement Payments
--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_Top5ReimbursementPay
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH agg AS (
--        SELECT
--            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
--            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS TotalPay,
--            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(AccessionNumber)), '')) AS Visits
--        FROM dbo.ClaimLevelData
--        WHERE PayerName_Raw IS NOT NULL
--          AND LTRIM(RTRIM(PayerName_Raw)) <> ''
--          AND ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--        GROUP BY LTRIM(RTRIM(PayerName_Raw))
--    ),
--    ranked AS (
--        SELECT TOP 5 PayerName, TotalPay, Visits,
--               ROW_NUMBER() OVER (ORDER BY TotalPay DESC) AS Rnk
--        FROM agg
--        ORDER BY TotalPay DESC
--    )
--    SELECT * INTO #out FROM ranked;

--    TRUNCATE TABLE dbo.NW_CS_Top5ReimbursementPay;
--    INSERT INTO dbo.NW_CS_Top5ReimbursementPay
--        (PayerRank, PayerName, TotalPayments, UniqueVisitCount, RefreshedAt)
--    SELECT CAST(Rnk AS TINYINT), PayerName, TotalPay, Visits, GETDATE()
--    FROM #out
--    ORDER BY Rnk;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_Top5ReimbursementPay completed.';
--END
GO


-- 3. Monthly Claim Volume  (ClaimLevelData, CheckDate, Top-3 payer per panel)
    CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_MonthlyClaimVolume
    AS
    BEGIN
        SET NOCOUNT ON;

        SELECT
            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown')))               AS PanelName,
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))               AS PayerName,
            YEAR (TRY_CAST(CheckDate AS DATE))                           AS BillYear,
            MONTH(TRY_CAST(CheckDate AS DATE))                           AS BillMonth,
            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))            AS NoOfClaims,
            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0)  AS InsurancePayment
        INTO #raw
        FROM dbo.ClaimLevelData
        WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
         -- AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
         -- AND YEAR(TRY_CAST(CheckDate AS DATE)) > 1900
        GROUP BY
            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown'))),
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))),
            YEAR (TRY_CAST(CheckDate AS DATE)),
            MONTH(TRY_CAST(CheckDate AS DATE));

        SELECT
            PanelName, PayerName,
            DENSE_RANK() OVER (PARTITION BY PanelName ORDER BY SUM(NoOfClaims) DESC) AS PayerRank
        INTO #ranks
        FROM #raw
        GROUP BY PanelName, PayerName;

        TRUNCATE TABLE dbo.NW_CS_MonthlyClaimVolume;
        INSERT INTO dbo.NW_CS_MonthlyClaimVolume
            (PanelName, PayerName, PayerRank, BillYear, BillMonth, NoOfClaims, InsurancePayment, RefreshedAt)
        SELECT r.PanelName, r.PayerName, CAST(k.PayerRank AS TINYINT),
               r.BillYear, CAST(r.BillMonth AS TINYINT), r.NoOfClaims, r.InsurancePayment, GETDATE()
        FROM #raw r
        JOIN #ranks k ON k.PanelName = r.PanelName AND k.PayerName = r.PayerName
        --WHERE k.PayerRank <= 3
        ORDER BY r.PanelName, k.PayerRank, r.BillYear, r.BillMonth;

        DROP TABLE IF EXISTS #raw;
        DROP TABLE IF EXISTS #ranks;
        PRINT 'usp_RefreshNW_CS_MonthlyClaimVolume completed.';
    END
    GO


-- 4. Weekly Claim Volume (ClaimLevelData, CheckDate, Mon-Sun, last 4 complete weeks)
--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_WeeklyClaimVolume
--AS
--BEGIN
--    SET NOCOUNT ON;

--    -- 1900-01-07 was a Sunday; used as anchor to calculate days-since-Sunday
--    DECLARE @Today DATE = CAST(GETDATE() AS DATE);
--    DECLARE @DaysSinceSun INT = ((DATEDIFF(DAY, '1900-01-07', @Today) % 7) + 7) % 7;
--    DECLARE @LastSun DATE = DATEADD(DAY, -@DaysSinceSun, @Today);
--    IF @LastSun = @Today SET @LastSun = DATEADD(DAY, -7, @LastSun);

--    DECLARE @W4End  DATE = @LastSun,                    @W4Start DATE = DATEADD(DAY,  -6, @LastSun);
--    DECLARE @W3End  DATE = DATEADD(DAY, -7, @LastSun),  @W3Start DATE = DATEADD(DAY, -13, @LastSun);
--    DECLARE @W2End  DATE = DATEADD(DAY,-14, @LastSun),  @W2Start DATE = DATEADD(DAY, -20, @LastSun);
--    DECLARE @W1End  DATE = DATEADD(DAY,-21, @LastSun),  @W1Start DATE = DATEADD(DAY, -27, @LastSun);

--    ;WITH src AS (
--        SELECT
--            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown')))            AS PanelName,
--            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))            AS PayerName,
--            CASE
--              WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W1End THEN 1
--              WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W2Start AND @W2End THEN 2
--              WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W3Start AND @W3End THEN 3
--              WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W4Start AND @W4End THEN 4
--            END                                                       AS WeekKey,
--            ClaimID,
--            TRY_CAST(InsurancePayment AS DECIMAL(18,2))               AS InsPay
--        FROM dbo.ClaimLevelData
--        WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--          AND TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W4End
--    ),
--    agg AS (
--        SELECT PanelName, PayerName, WeekKey,
--               COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), '')) AS NoOfClaims,
--               ISNULL(SUM(InsPay), 0)                            AS InsurancePayment
--        FROM src
--        WHERE WeekKey IS NOT NULL
--        GROUP BY PanelName, PayerName, WeekKey
--    ),
--    ranks AS (
--        SELECT PanelName, PayerName,
--               DENSE_RANK() OVER (PARTITION BY PanelName ORDER BY SUM(NoOfClaims) DESC) AS PayerRank
--        FROM agg
--        GROUP BY PanelName, PayerName
--    )
--    SELECT a.PanelName, a.PayerName, CAST(r.PayerRank AS TINYINT) AS PayerRank,
--           CAST(a.WeekKey AS TINYINT) AS WeekKey,
--           CASE a.WeekKey WHEN 1 THEN @W1Start WHEN 2 THEN @W2Start
--                          WHEN 3 THEN @W3Start WHEN 4 THEN @W4Start END AS WeekStart,
--           CASE a.WeekKey WHEN 1 THEN @W1End   WHEN 2 THEN @W2End
--                          WHEN 3 THEN @W3End   WHEN 4 THEN @W4End   END AS WeekEnd,
--           a.NoOfClaims, a.InsurancePayment
--    INTO #out
--    FROM agg a
--    JOIN ranks r ON r.PanelName = a.PanelName AND r.PayerName = a.PayerName;
--  --  WHERE r.PayerRank <= 3;

--    TRUNCATE TABLE dbo.NW_CS_WeeklyClaimVolume;
--    INSERT INTO dbo.NW_CS_WeeklyClaimVolume
--        (PanelName, PayerName, PayerRank, WeekKey, WeekStart, WeekEnd,
--         NoOfClaims, InsurancePayment, RefreshedAt)
--    SELECT PanelName, PayerName, PayerRank, WeekKey, WeekStart, WeekEnd,
--           NoOfClaims, InsurancePayment, GETDATE()
--    FROM #out
--    ORDER BY PanelName, PayerRank, WeekKey;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_WeeklyClaimVolume completed.';
--END
--GO


CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_WeeklyClaimVolume
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Today DATE = CAST(GETDATE() AS DATE);
    DECLARE @MaxCheckDate DATE;
    DECLARE @WeekContainingMaxStart DATE;
    DECLARE @WeekContainingMaxEnd DATE;
    DECLARE @LatestCompletedWeekStart DATE;
    DECLARE @LatestCompletedWeekEnd DATE;

    SELECT
        @MaxCheckDate = MAX(TRY_CAST(CheckDate AS DATE))
    FROM dbo.ClaimLevelData
    WHERE TRY_CAST(CheckDate AS DATE) IS NOT NULL
      AND TRY_CAST(CheckDate AS DATE) <= @Today;

    IF @MaxCheckDate IS NULL
    BEGIN
        RAISERROR('No valid CheckDate <= today found in ClaimLevelData.', 16, 1);
        RETURN;
    END;

    /*
        Thursday-Wednesday week logic.
        1900-01-04 is Thursday.
    */
    SET @WeekContainingMaxStart =
        DATEADD(
            DAY,
            -(DATEDIFF(DAY, '19000104', @MaxCheckDate) % 7),
            @MaxCheckDate
        );

    SET @WeekContainingMaxEnd = DATEADD(DAY, 6, @WeekContainingMaxStart);

    IF @WeekContainingMaxEnd <= @Today
    BEGIN
        SET @LatestCompletedWeekStart = @WeekContainingMaxStart;
        SET @LatestCompletedWeekEnd   = @WeekContainingMaxEnd;
    END
    ELSE
    BEGIN
        SET @LatestCompletedWeekStart = DATEADD(DAY, -7, @WeekContainingMaxStart);
        SET @LatestCompletedWeekEnd   = DATEADD(DAY,  6, @LatestCompletedWeekStart);
    END;

    DECLARE @W4Start DATE = @LatestCompletedWeekStart;
    DECLARE @W4End   DATE = @LatestCompletedWeekEnd;

    DECLARE @W3Start DATE = DATEADD(DAY, -7, @W4Start);
    DECLARE @W3End   DATE = DATEADD(DAY,  6, @W3Start);

    DECLARE @W2Start DATE = DATEADD(DAY, -7, @W3Start);
    DECLARE @W2End   DATE = DATEADD(DAY,  6, @W2Start);

    DECLARE @W1Start DATE = DATEADD(DAY, -7, @W2Start);
    DECLARE @W1End   DATE = DATEADD(DAY,  6, @W1Start);

    ;WITH src AS
    (
        SELECT
            -- Changed from Panelname to PanelType
            LTRIM(RTRIM(ISNULL(PanelType, 'Unknown'))) AS PanelName,

            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))) AS PayerName,

            CASE
                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W1End THEN 1
                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W2Start AND @W2End THEN 2
                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W3Start AND @W3End THEN 3
                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W4Start AND @W4End THEN 4
            END AS WeekKey,

            ClaimID,

            TRY_CONVERT(
                DECIMAL(18,2),
                REPLACE(REPLACE(REPLACE(ISNULL(InsurancePayment, ''), ',', ''), '$', ''), ' ', '')
            ) AS InsPay
        FROM dbo.ClaimLevelData
        WHERE ISNULL(
                  TRY_CONVERT(
                      DECIMAL(18,2),
                      REPLACE(REPLACE(REPLACE(ISNULL(InsurancePayment, ''), ',', ''), '$', ''), ' ', '')
                  ), 0
              ) > 0
          AND TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W4End
    ),
    agg AS
    (
        SELECT
            PanelName,
            PayerName,
            WeekKey,
            COUNT(NULLIF(LTRIM(RTRIM(ClaimID)), '')) AS NoOfClaims,
            ISNULL(SUM(InsPay), 0) AS InsurancePayment
        FROM src
        WHERE WeekKey IS NOT NULL
        GROUP BY
            PanelName,
            PayerName,
            WeekKey
    ),
    ranks AS
    (
        SELECT
            PanelName,
            PayerName,
            DENSE_RANK() OVER
            (
                PARTITION BY PanelName
                ORDER BY SUM(NoOfClaims) DESC
            ) AS PayerRank
        FROM agg
        GROUP BY
            PanelName,
            PayerName
    )
    SELECT
        a.PanelName,
        a.PayerName,
        CAST(r.PayerRank AS TINYINT) AS PayerRank,
        CAST(a.WeekKey AS TINYINT) AS WeekKey,

        CASE a.WeekKey
            WHEN 1 THEN @W1Start
            WHEN 2 THEN @W2Start
            WHEN 3 THEN @W3Start
            WHEN 4 THEN @W4Start
        END AS WeekStart,

        CASE a.WeekKey
            WHEN 1 THEN @W1End
            WHEN 2 THEN @W2End
            WHEN 3 THEN @W3End
            WHEN 4 THEN @W4End
        END AS WeekEnd,

        a.NoOfClaims,
        a.InsurancePayment
    INTO #out
    FROM agg a
    JOIN ranks r
      ON r.PanelName = a.PanelName
     AND r.PayerName = a.PayerName;

    TRUNCATE TABLE dbo.NW_CS_WeeklyClaimVolume;

    INSERT INTO dbo.NW_CS_WeeklyClaimVolume
    (
        PanelName,
        PayerName,
        PayerRank,
        WeekKey,
        WeekStart,
        WeekEnd,
        NoOfClaims,
        InsurancePayment,
        RefreshedAt
    )
    SELECT
        PanelName,
        PayerName,
        PayerRank,
        WeekKey,
        WeekStart,
        WeekEnd,
        NoOfClaims,
        InsurancePayment,
        GETDATE()
    FROM #out
    ORDER BY
        PanelName,
        PayerRank,
        WeekKey;

    DROP TABLE IF EXISTS #out;

    PRINT 'usp_RefreshNW_CS_WeeklyClaimVolume completed.';

    PRINT 'Week 1: ' + CONVERT(VARCHAR(10), @W1Start, 120) + ' to ' + CONVERT(VARCHAR(10), @W1End, 120);
    PRINT 'Week 2: ' + CONVERT(VARCHAR(10), @W2Start, 120) + ' to ' + CONVERT(VARCHAR(10), @W2End, 120);
    PRINT 'Week 3: ' + CONVERT(VARCHAR(10), @W3Start, 120) + ' to ' + CONVERT(VARCHAR(10), @W3End, 120);
    PRINT 'Week 4: ' + CONVERT(VARCHAR(10), @W4Start, 120) + ' to ' + CONVERT(VARCHAR(10), @W4End, 120);
END
GO

--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_WeeklyClaimVolume
--AS
--BEGIN
--    SET NOCOUNT ON;

--    DECLARE @Today DATE = CAST(GETDATE() AS DATE);
--    DECLARE @MaxCheckDate DATE;
--    DECLARE @WeekContainingMaxStart DATE;
--    DECLARE @WeekContainingMaxEnd DATE;
--    DECLARE @LatestCompletedWeekStart DATE;
--    DECLARE @LatestCompletedWeekEnd DATE;

--    /*
--      Get latest available CheckDate up to today
--    */
--    SELECT
--        @MaxCheckDate = MAX(TRY_CAST(CheckDate AS DATE))
--    FROM dbo.ClaimLevelData
--    WHERE TRY_CAST(CheckDate AS DATE) IS NOT NULL
--      AND TRY_CAST(CheckDate AS DATE) <= @Today;

--    IF @MaxCheckDate IS NULL
--    BEGIN
--        RAISERROR('No valid CheckDate <= today found in ClaimLevelData.', 16, 1);
--        RETURN;
--    END;

--    /*
--      Thu-Wed week logic
--      1900-01-04 is Thursday
--    */
--    SET @WeekContainingMaxStart =
--        DATEADD(DAY,
--            -(DATEDIFF(DAY, '19000104', @MaxCheckDate) % 7),
--            @MaxCheckDate);

--    SET @WeekContainingMaxEnd = DATEADD(DAY, 6, @WeekContainingMaxStart);

--    /*
--      Option B: only completed weeks
--      If the week containing MaxCheckDate is not complete as of today,
--      use previous Thu-Wed week.
--    */
--    IF @WeekContainingMaxEnd <= @Today
--    BEGIN
--        SET @LatestCompletedWeekStart = @WeekContainingMaxStart;
--        SET @LatestCompletedWeekEnd   = @WeekContainingMaxEnd;
--    END
--    ELSE
--    BEGIN
--        SET @LatestCompletedWeekStart = DATEADD(DAY, -7, @WeekContainingMaxStart);
--        SET @LatestCompletedWeekEnd   = DATEADD(DAY,  6, @LatestCompletedWeekStart);
--    END;

--    DECLARE @W4Start DATE = @LatestCompletedWeekStart;
--    DECLARE @W4End   DATE = @LatestCompletedWeekEnd;

--    DECLARE @W3Start DATE = DATEADD(DAY, -7, @W4Start);
--    DECLARE @W3End   DATE = DATEADD(DAY,  6, @W3Start);

--    DECLARE @W2Start DATE = DATEADD(DAY, -7, @W3Start);
--    DECLARE @W2End   DATE = DATEADD(DAY,  6, @W2Start);

--    DECLARE @W1Start DATE = DATEADD(DAY, -7, @W2Start);
--    DECLARE @W1End   DATE = DATEADD(DAY,  6, @W1Start);

--    ;WITH src AS
--    (
--        SELECT
--            LTRIM(RTRIM(ISNULL(PanelType, 'Unknown'))) AS PanelName,
--            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))) AS PayerName,
--            CASE
--                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W1End THEN 1
--                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W2Start AND @W2End THEN 2
--                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W3Start AND @W3End THEN 3
--                WHEN TRY_CAST(CheckDate AS DATE) BETWEEN @W4Start AND @W4End THEN 4
--            END AS WeekKey,
--            ClaimID,
--            TRY_CAST(InsurancePayment AS DECIMAL(18,2)) AS InsPay
--        FROM dbo.ClaimLevelData
--        WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--          AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
--          AND TRY_CAST(CheckDate AS DATE) <= @Today
--          AND TRY_CAST(CheckDate AS DATE) BETWEEN @W1Start AND @W4End
--    ),
--    agg AS
--    (
--        SELECT
--            PanelName,
--            PayerName,
--            WeekKey,
--            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), '')) AS NoOfClaims,
--            ISNULL(SUM(InsPay), 0) AS InsurancePayment
--        FROM src
--        WHERE WeekKey IS NOT NULL
--        GROUP BY PanelName, PayerName, WeekKey
--    ),
--    ranks AS
--    (
--        SELECT
--            PanelName,
--            PayerName,
--            DENSE_RANK() OVER (PARTITION BY PanelName ORDER BY SUM(NoOfClaims) DESC) AS PayerRank
--        FROM agg
--        GROUP BY PanelName, PayerName
--    )
--    SELECT
--        a.PanelName,
--        a.PayerName,
--        CAST(r.PayerRank AS TINYINT) AS PayerRank,
--        CAST(a.WeekKey AS TINYINT) AS WeekKey,
--        CASE a.WeekKey
--            WHEN 1 THEN @W1Start
--            WHEN 2 THEN @W2Start
--            WHEN 3 THEN @W3Start
--            WHEN 4 THEN @W4Start
--        END AS WeekStart,
--        CASE a.WeekKey
--            WHEN 1 THEN @W1End
--            WHEN 2 THEN @W2End
--            WHEN 3 THEN @W3End
--            WHEN 4 THEN @W4End
--        END AS WeekEnd,
--        a.NoOfClaims,
--        a.InsurancePayment
--    INTO #out
--    FROM agg a
--    JOIN ranks r
--      ON r.PanelName = a.PanelName
--     AND r.PayerName = a.PayerName;

--    TRUNCATE TABLE dbo.NW_CS_WeeklyClaimVolume;

--    INSERT INTO dbo.NW_CS_WeeklyClaimVolume
--    (
--        PanelName,
--        PayerName,
--        PayerRank,
--        WeekKey,
--        WeekStart,
--        WeekEnd,
--        NoOfClaims,
--        InsurancePayment,
--        RefreshedAt
--    )
--    SELECT
--        PanelName,
--        PayerName,
--        PayerRank,
--        WeekKey,
--        WeekStart,
--        WeekEnd,
--        NoOfClaims,
--        InsurancePayment,
--        GETDATE()
--    FROM #out
--    ORDER BY PanelName, PayerRank, WeekKey;

--    DROP TABLE IF EXISTS #out;

--    PRINT 'usp_RefreshNW_CS_WeeklyClaimVolume completed.';
--END
--GO
-- 5. Panel Averages


-- =============================================
-- STEP 1: Alter table to add Adjudicated columns
-- =============================================
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NW_CS_PanelAverages') AND name = 'AdjudicatedCount')
    ALTER TABLE dbo.NW_CS_PanelAverages ADD AdjudicatedCount INT            NOT NULL DEFAULT 0;
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NW_CS_PanelAverages') AND name = 'AdjudicatedAmount')
    ALTER TABLE dbo.NW_CS_PanelAverages ADD AdjudicatedAmount DECIMAL(18,2) NOT NULL DEFAULT 0;
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.NW_CS_PanelAverages') AND name = 'AvgAdjudicated')
    ALTER TABLE dbo.NW_CS_PanelAverages ADD AvgAdjudicated   DECIMAL(18,2) NOT NULL DEFAULT 0;
GO


CREATE or Alter   PROCEDURE dbo.usp_RefreshNW_CS_PanelAverages    
AS    
BEGIN    
    SET NOCOUNT ON;    
    
    DECLARE @MaxCheckDate DATE;    
    DECLARE @StartCheckDate DATE;    
    DECLARE @EndCheckDate DATE;    
    
    /*    
        Get latest valid CheckDate from ClaimLevelData up to today    
    */    
    SELECT    
        @MaxCheckDate = MAX(TRY_CAST(CheckDate AS DATE))    
    FROM dbo.ClaimLevelData    
    WHERE TRY_CAST(CheckDate AS DATE) IS NOT NULL    
      AND TRY_CAST(CheckDate AS DATE) <= CAST(GETDATE() AS DATE);    
    
    IF @MaxCheckDate IS NULL    
    BEGIN    
        RAISERROR('No valid CheckDate <= today found in ClaimLevelData.', 16, 1);    
        RETURN;    
    END;    
    
    /*    
        Rolling 180 days based on max CheckDate.    
        Example:    
        If @MaxCheckDate = 2026-05-31,    
        then range = 2025-12-02 to 2026-05-31.    
    */    
    SET @StartCheckDate = DATEADD(DAY, -180, @MaxCheckDate);    
    SET @EndCheckDate   = @MaxCheckDate;    
    
    ;WITH src AS    
    (    
        SELECT    
            LTRIM(RTRIM(ISNULL(Panelname, 'Unknown'))) AS PanelName,    
    
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))) AS PayerName,    
    
            COALESCE(    
                NULLIF(LTRIM(RTRIM(AccessionNumber)), ''),    
                LTRIM(RTRIM(ClaimID))    
            ) AS VisitKey,    
    
            TRY_CAST(ChargeAmount AS DECIMAL(18,2)) AS Chg,    
            TRY_CAST(InsurancePayment AS DECIMAL(18,2)) AS InsPay,    
    
            LTRIM(RTRIM(ISNULL(ClaimStatus, ''))) AS ClaimStatus,    

            FullyPaidCount,    
            TRY_CAST(FullyPaidAmount AS DECIMAL(18,2)) AS FullyPaidAmount,    
    
            Adjudicated as AdjudicatedCount,    
            TRY_CAST(AdjudicatedAmount AS DECIMAL(18,2)) AS AdjudicatedAmount,    
    
            Bucket30 AS Bucket30Count,    
            TRY_CAST(Bucket30 AS DECIMAL(18,2)) AS Bucket30Amount,    
    
            Bucket60 AS Bucket60Count,    
            TRY_CAST(Bucket60 AS DECIMAL(18,2)) AS Bucket60Amount,    
    
            TRY_CAST(CheckDate AS DATE) AS CheckDateValue    
    
        FROM dbo.ClaimLevelData    
    )    
    SELECT    
        PanelName,    
        PayerName,    
    
        COUNT(VisitKey) AS ClaimCount,    
    
        ISNULL(SUM(Chg), 0) AS TotalCharges,    
    
        ISNULL(SUM(InsPay), 0) AS CarrierPayment,    
    
        COUNT(    
            CASE    
                WHEN FullyPaidCount IN ('Fully Paid', 'Fully Paid Count')    
                THEN VisitKey    
            END    
        ) AS FullyPaidCount,    
    
        ISNULL(    
            SUM(    
                CASE    
                    WHEN FullyPaidCount IN ('Fully Paid', 'Fully Paid Count')    
                    THEN FullyPaidAmount    
                    ELSE 0    
                END    
            ), 0    
        ) AS FullyPaidAmount,    
    
        COUNT(    
            CASE    
                WHEN AdjudicatedCount IN ('Adjudicated', 'Adjudicated Count')    
                THEN VisitKey    
            END    
        ) AS AdjudicatedCount,    
    
        ISNULL(    
            SUM(    
                CASE    
                    WHEN AdjudicatedCount IN ('Adjudicated', 'Adjudicated Count')    
                    THEN AdjudicatedAmount    
                    ELSE 0    
                END    
            ), 0    
        ) AS AdjudicatedAmount,    
    
        COUNT(    
            CASE    
                WHEN Bucket30Count IN ('30 Bucket', '30 Days Count')    
                THEN VisitKey    
            END    
        ) AS Days30Count,    
    
        ISNULL(    
            SUM(    
                CASE    
                    WHEN Bucket30Count IN ('30 Bucket', '30 Days Count')    
                    THEN Bucket30Amount    
                    ELSE 0    
                END    
            ), 0    
        ) AS Days30Amount,    
    
        COUNT(    
            CASE    
                WHEN Bucket60Count IN ('60 Bucket', '60 Days Count')    
                THEN VisitKey    
            END    
        ) AS Days60Count,    
    
        ISNULL(    
            SUM(    
                CASE    
                    WHEN Bucket60Count IN ('60 Bucket', '60 Days Count')    
                    THEN Bucket60Amount    
                    ELSE 0    
                END    
            ), 0    
        ) AS Days60Amount    
    
    INTO #out    
    
    FROM src    
    
    WHERE CheckDateValue IS NOT NULL    
      AND CheckDateValue BETWEEN @StartCheckDate AND @EndCheckDate    
    
        
    GROUP BY PanelName, PayerName;    
    
    TRUNCATE TABLE dbo.NW_CS_PanelAverages;    
    
    INSERT INTO dbo.NW_CS_PanelAverages    
    (    
        PanelName,    
        PayerName,    
    
        NoOfClaims,    
        TotalCharges,    
        CarrierPayment,    
        AvgCarrierPayment,    
    
        FullyPaidCount,    
        FullyPaidAmount,    
        AvgFullyPaid,    
    
        AdjudicatedCount,    
        AdjudicatedAmount,    
        AvgAdjudicated,    
    
        Days30Count,    
        Days30Amount,    
        AvgDays30,    
    
        Days60Count,    
        Days60Amount,    
        AvgDays60,    
    
        RefreshedAt    
    )    
    SELECT    
        PanelName,    
        PayerName,    
    
        ClaimCount,    
        TotalCharges,    
        CarrierPayment,    
    
        CASE    
            WHEN ClaimCount > 0    
            THEN CarrierPayment / ClaimCount    
            ELSE 0    
        END AS AvgCarrierPayment,    
    
        FullyPaidCount,    
        FullyPaidAmount,    
    
        CASE    
            WHEN FullyPaidCount > 0    
            THEN FullyPaidAmount / FullyPaidCount    
            ELSE 0    
        END AS AvgFullyPaid,    
    
        AdjudicatedCount,    
        AdjudicatedAmount,    
    
        CASE    
            WHEN AdjudicatedCount > 0    
            THEN AdjudicatedAmount / AdjudicatedCount    
            ELSE 0    
        END AS AvgAdjudicated,    
    
        Days30Count,    
        Days30Amount,    
    
        CASE    
            WHEN Days30Count > 0    
            THEN Days30Amount / Days30Count    
            ELSE 0    
        END AS AvgDays30,    
    
        Days60Count,    
        Days60Amount,    
    
        CASE    
            WHEN Days60Count > 0    
            THEN Days60Amount / Days60Count    
            ELSE 0    
        END AS AvgDays60,    
    
        GETDATE()    
    
    FROM #out    
    ORDER BY PanelName, PayerName;    
    
    DROP TABLE IF EXISTS #out;    
    
    PRINT 'usp_RefreshNW_CS_PanelAverages completed.';    
    PRINT 'CheckDate Start: ' + CONVERT(VARCHAR(10), @StartCheckDate, 120);    
    PRINT 'CheckDate End: ' + CONVERT(VARCHAR(10), @EndCheckDate, 120);    
END 

GO
--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_PanelAverages
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH src AS (
--        SELECT
--            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown')))            AS PanelName,
--            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))            AS PayerName,
--            COALESCE(NULLIF(LTRIM(RTRIM(AccessionNumber)), ''),
--                     LTRIM(RTRIM(ClaimID)))                           AS VisitKey,
--            TRY_CAST(ChargeAmount     AS DECIMAL(18,2))               AS Chg,
--            TRY_CAST(InsurancePayment AS DECIMAL(18,2))               AS InsPay,
--            LTRIM(RTRIM(ClaimStatus))                                 AS ClaimStatus,
--            LTRIM(RTRIM(Adjudicated))                                 AS Adjudicated,
--            TRY_CAST(AdjudicatedAmount AS DECIMAL(18,2))              AS AdjAmt,
--            LTRIM(RTRIM(Bucket30))                                    AS Bucket30,
--            TRY_CAST(Bucket30Amount AS DECIMAL(18,2))                 AS Bucket30Amt,
--            LTRIM(RTRIM(Bucket60))                                    AS Bucket60,
--            TRY_CAST(Bucket60Amount AS DECIMAL(18,2))                 AS Bucket60Amt
--        FROM dbo.ClaimLevelData
--        WHERE PanelType IS NOT NULL AND LTRIM(RTRIM(PanelType)) <> ''
--		  AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
--       -- Last 6 months filter
--            AND TRY_CAST(CheckDate AS DATE)
--                >= DATEADD(MONTH, -6, CAST(GETDATE() AS DATE))
--    )
--    SELECT
--        PanelName,
--        PayerName,

--        COUNT(DISTINCT CASE WHEN ClaimStatus <> 'No Response' THEN VisitKey END)      AS NoOfClaims,
--        ISNULL(SUM(CASE WHEN ClaimStatus <> 'No Response' THEN Chg    ELSE 0 END), 0) AS TotalCharges,
--        ISNULL(SUM(CASE WHEN ClaimStatus <> 'No Response' THEN InsPay ELSE 0 END), 0) AS CarrierPayment,

--        COUNT(DISTINCT CASE WHEN ClaimStatus = 'Fully Paid' THEN VisitKey END)        AS FullyPaidCount,
--        ISNULL(SUM(CASE WHEN ClaimStatus = 'Fully Paid' THEN InsPay ELSE 0 END), 0)   AS FullyPaidAmount,

--        COUNT(DISTINCT CASE WHEN Adjudicated = 'Adjudicated' THEN VisitKey END)       AS AdjudicatedCount,
--        ISNULL(SUM(CASE WHEN Adjudicated = 'Adjudicated' THEN AdjAmt ELSE 0 END), 0)  AS AdjudicatedAmount,

--        COUNT(DISTINCT CASE WHEN Bucket30 = '30 Bucket' THEN VisitKey END)            AS Days30Count,
--        ISNULL(SUM(CASE WHEN Bucket30 = '30 Bucket' THEN Bucket30Amt ELSE 0 END), 0)  AS Days30Amount,

--        COUNT(DISTINCT CASE WHEN Bucket60 = '60 Bucket' THEN VisitKey END)            AS Days60Count,
--        ISNULL(SUM(CASE WHEN Bucket60 = '60 Bucket' THEN Bucket60Amt ELSE 0 END), 0)  AS Days60Amount
--    INTO #out
--    FROM src
--    GROUP BY PanelName, PayerName;

--    TRUNCATE TABLE dbo.NW_CS_PanelAverages;

--    INSERT INTO dbo.NW_CS_PanelAverages
--        (PanelName, PayerName,
--         NoOfClaims, TotalCharges, CarrierPayment, AvgCarrierPayment,
--         FullyPaidCount, FullyPaidAmount, AvgFullyPaid,
--         AdjudicatedCount, AdjudicatedAmount, AvgAdjudicated,
--         Days30Count, Days30Amount, AvgDays30,
--         Days60Count, Days60Amount, AvgDays60,
--         RefreshedAt)
--    SELECT
--        PanelName, PayerName,
--        NoOfClaims, TotalCharges, CarrierPayment,
--        CASE WHEN NoOfClaims       > 0 THEN CarrierPayment    / NoOfClaims       ELSE 0 END,
--        FullyPaidCount, FullyPaidAmount,
--        CASE WHEN FullyPaidCount   > 0 THEN FullyPaidAmount   / FullyPaidCount   ELSE 0 END,
--        AdjudicatedCount, AdjudicatedAmount,
--        CASE WHEN AdjudicatedCount > 0 THEN AdjudicatedAmount / AdjudicatedCount ELSE 0 END,
--        Days30Count, Days30Amount,
--        CASE WHEN Days30Count      > 0 THEN Days30Amount      / Days30Count      ELSE 0 END,
--        Days60Count, Days60Amount,
--        CASE WHEN Days60Count      > 0 THEN Days60Amount      / Days60Count      ELSE 0 END,
--        GETDATE()
--    FROM #out
--    ORDER BY PanelName, PayerName;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_PanelAverages completed.';
--END
--GO


--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_PanelAverages
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH src AS (
--        SELECT
--            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown')))            AS PanelName,
--            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))            AS PayerName,
--            COALESCE(NULLIF(LTRIM(RTRIM(AccessionNumber)), ''),
--                     LTRIM(RTRIM(ClaimID)))                           AS VisitKey,
--            TRY_CAST(ChargeAmount     AS DECIMAL(18,2))               AS Chg,
--            TRY_CAST(InsurancePayment AS DECIMAL(18,2))               AS InsPay,
--            LTRIM(RTRIM(ClaimStatus))                                 AS ClaimStatus,
--            LTRIM(RTRIM(Adjudicated))                                 AS Adjudicated,
--            TRY_CAST(AdjudicatedAmount AS DECIMAL(18,2))              AS AdjAmt,
--            LTRIM(RTRIM(Bucket30))                                    AS Bucket30,
--            TRY_CAST(Bucket30Amount AS DECIMAL(18,2))                 AS Bucket30Amt,
--            LTRIM(RTRIM(Bucket60))                                    AS Bucket60,
--            TRY_CAST(Bucket60Amount AS DECIMAL(18,2))                 AS Bucket60Amt
--        FROM dbo.ClaimLevelData
--        WHERE PanelType IS NOT NULL AND LTRIM(RTRIM(PanelType)) <> ''
--    )
--    SELECT
--        PanelName,
--        PayerName,

--        COUNT(DISTINCT CASE WHEN ClaimStatus <> 'No Response' THEN VisitKey END)      AS NoOfClaims,
--        ISNULL(SUM(CASE WHEN ClaimStatus <> 'No Response' THEN Chg    ELSE 0 END), 0) AS TotalCharges,
--        ISNULL(SUM(CASE WHEN ClaimStatus <> 'No Response' THEN InsPay ELSE 0 END), 0) AS CarrierPayment,

--        COUNT(DISTINCT CASE WHEN ClaimStatus = 'Fully Paid' THEN VisitKey END)        AS FullyPaidCount,
--        ISNULL(SUM(CASE WHEN ClaimStatus = 'Fully Paid' THEN InsPay ELSE 0 END), 0)   AS FullyPaidAmount,

--        COUNT(DISTINCT CASE WHEN Adjudicated = 'Adjudicated' THEN VisitKey END)       AS AdjudicatedCount,
--        ISNULL(SUM(CASE WHEN Adjudicated = 'Adjudicated' THEN AdjAmt ELSE 0 END), 0)  AS AdjudicatedAmount,

--        COUNT(DISTINCT CASE WHEN Bucket30 = '30 Bucket' THEN VisitKey END)            AS Days30Count,
--        ISNULL(SUM(CASE WHEN Bucket30 = '30 Bucket' THEN Bucket30Amt ELSE 0 END), 0)  AS Days30Amount,

--        COUNT(DISTINCT CASE WHEN Bucket60 = '60 Bucket' THEN VisitKey END)            AS Days60Count,
--        ISNULL(SUM(CASE WHEN Bucket60 = '60 Bucket' THEN Bucket60Amt ELSE 0 END), 0)  AS Days60Amount
--    INTO #out
--    FROM src
--    GROUP BY PanelName, PayerName;

--    TRUNCATE TABLE dbo.NW_CS_PanelAverages;

--    INSERT INTO dbo.NW_CS_PanelAverages
--        (PanelName, PayerName,
--         NoOfClaims, TotalCharges, CarrierPayment, AvgCarrierPayment,
--         FullyPaidCount, FullyPaidAmount, AvgFullyPaid,
--         AdjudicatedCount, AdjudicatedAmount, AvgAdjudicated,
--         Days30Count, Days30Amount, AvgDays30,
--         Days60Count, Days60Amount, AvgDays60,
--         RefreshedAt)
--    SELECT
--        PanelName, PayerName,
--        NoOfClaims, TotalCharges, CarrierPayment,
--        CASE WHEN NoOfClaims       > 0 THEN CarrierPayment    / NoOfClaims       ELSE 0 END,
--        FullyPaidCount, FullyPaidAmount,
--        CASE WHEN FullyPaidCount   > 0 THEN FullyPaidAmount   / FullyPaidCount   ELSE 0 END,
--        AdjudicatedCount, AdjudicatedAmount,
--        CASE WHEN AdjudicatedCount > 0 THEN AdjudicatedAmount / AdjudicatedCount ELSE 0 END,
--        Days30Count, Days30Amount,
--        CASE WHEN Days30Count      > 0 THEN Days30Amount      / Days30Count      ELSE 0 END,
--        Days60Count, Days60Amount,
--        CASE WHEN Days60Count      > 0 THEN Days60Amount      / Days60Count      ELSE 0 END,
--        GETDATE()
--    FROM #out
--    ORDER BY PanelName, PayerName;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_PanelAverages completed.';
--END
--GO


-- 6. AvgPayments  (CheckDate last 6 months — same shape as legacy dashboard query)
CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_AvgPayments
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Cutoff DATE = DATEADD(MONTH, -6, CAST(GETDATE() AS DATE));

    ;WITH base AS (
        SELECT
            LTRIM(RTRIM(ISNULL(PanelType,        'Unknown')))            AS PanelName,
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))            AS PayerName,
            ClaimID,
            TRY_CAST(ChargeAmount     AS DECIMAL(18,2))               AS Chg,
            TRY_CAST(InsurancePayment AS DECIMAL(18,2))               AS InsPay,
            LTRIM(RTRIM(ClaimStatus))                                 AS Status,
            ISNULL(TRY_CAST(DaystoDOS AS INT), 9999)                  AS Days
        FROM dbo.ClaimLevelData
        WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
          AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
          AND TRY_CAST(CheckDate AS DATE) >= @Cutoff
          AND PanelType IS NOT NULL AND LTRIM(RTRIM(PanelType)) <> ''
          AND PayerName_Raw IS NOT NULL AND LTRIM(RTRIM(PayerName_Raw)) <> ''
    ),
    agg AS (
        SELECT PanelName, PayerName,
               COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), '')) AS ClaimCount,
               ISNULL(SUM(Chg),    0) AS TotalCharges,
               ISNULL(SUM(InsPay), 0) AS InsurancePayment,
               COUNT(DISTINCT CASE WHEN Status = 'Fully Paid' THEN ClaimID END) AS FullyPaidCount,
               ISNULL(SUM(CASE WHEN Status = 'Fully Paid' THEN InsPay ELSE 0 END), 0) AS FullyPaidAmount,
               COUNT(DISTINCT CASE WHEN Status IN
                   ('Fully Paid','Partially Paid','Complete W/O','Fully Adjusted',
                    'Fully Denied','Denied','Partially Denied','Partially Adjusted',
                    'Patient Responsibility')
                 THEN ClaimID END) AS AdjudicatedCount,
               ISNULL(SUM(CASE WHEN Status IN
                   ('Fully Paid','Partially Paid','Complete W/O','Fully Adjusted',
                    'Fully Denied','Denied','Partially Denied','Partially Adjusted',
                    'Patient Responsibility')
                 THEN InsPay ELSE 0 END), 0) AS AdjudicatedAmount,
               COUNT(DISTINCT CASE WHEN Days <= 30 THEN ClaimID END) AS Over30Count,
               ISNULL(SUM(CASE WHEN Days <= 30 THEN InsPay ELSE 0 END), 0) AS Over30Amount,
               COUNT(DISTINCT CASE WHEN Days <= 60 THEN ClaimID END) AS Over60Count,
               ISNULL(SUM(CASE WHEN Days <= 60 THEN InsPay ELSE 0 END), 0) AS Over60Amount
        FROM base
        GROUP BY PanelName, PayerName
    ),
    ranks AS (
        SELECT PanelName, PayerName,
               DENSE_RANK() OVER (PARTITION BY PanelName ORDER BY ClaimCount DESC) AS PayerRank
        FROM agg
    )
    SELECT a.*, CAST(r.PayerRank AS TINYINT) AS PayerRank
    INTO #out
    FROM agg a
    JOIN ranks r ON r.PanelName = a.PanelName AND r.PayerName = a.PayerName
    WHERE r.PayerRank <= 3;

    TRUNCATE TABLE dbo.NW_CS_AvgPayments;
    INSERT INTO dbo.NW_CS_AvgPayments
        (PanelName, PayerName, PayerRank,
         ClaimCount, TotalCharges, AvgCharges,
         InsurancePayment, AvgInsurancePayment,
         FullyPaidCount, FullyPaidAmount, AvgFullyPaid,
         AdjudicatedCount, AdjudicatedAmount, AvgAdjudicated,
         Over30Count, Over30Amount, AvgOver30,
         Over60Count, Over60Amount, AvgOver60,
         RefreshedAt)
    SELECT
        PanelName, PayerName, PayerRank,
        ClaimCount, TotalCharges,
        CASE WHEN ClaimCount > 0 THEN TotalCharges / ClaimCount ELSE 0 END,
        InsurancePayment,
        CASE WHEN ClaimCount > 0 THEN InsurancePayment / ClaimCount ELSE 0 END,
        FullyPaidCount, FullyPaidAmount,
        CASE WHEN FullyPaidCount > 0 THEN FullyPaidAmount / FullyPaidCount ELSE 0 END,
        AdjudicatedCount, AdjudicatedAmount,
        CASE WHEN AdjudicatedCount > 0 THEN AdjudicatedAmount / AdjudicatedCount ELSE 0 END,
        Over30Count, Over30Amount,
        CASE WHEN Over30Count > 0 THEN Over30Amount / Over30Count ELSE 0 END,
        Over60Count, Over60Amount,
        CASE WHEN Over60Count > 0 THEN Over60Amount / Over60Count ELSE 0 END,
        GETDATE()
    FROM #out
    ORDER BY PanelName, PayerRank;

    DROP TABLE IF EXISTS #out;
    PRINT 'usp_RefreshNW_CS_AvgPayments completed.';
END
GO


-- 7. Insurance vs Aging


  
CREATE  or Alter  PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsAging    
AS    
BEGIN    
    SET NOCOUNT ON;    
    
    TRUNCATE TABLE dbo.NW_CS_InsuranceVsAging;    
    
    INSERT INTO dbo.NW_CS_InsuranceVsAging    
        (PayerName, AgingBucket, VisitCount, InsuranceBalance, RefreshedAt)    
    SELECT    
        LTRIM(RTRIM(PayerName_Raw))                                  AS PayerName,          
  LTRIM(RTRIM(ISNULL(Aging, '(blank)')))                 AS AgingBucket,    
        COUNT( NULLIF(LTRIM(RTRIM(AccessionNumber)), ''))    AS VisitCount,    
        ISNULL(SUM(TRY_CAST(InsuranceBalance AS DECIMAL(18,2))), 0)  AS InsuranceBalance,    
        GETDATE()    
    FROM dbo.ClaimLevelData    
    WHERE   LTRIM(RTRIM(ClaimStatus)) = 'No Response'    
    GROUP BY LTRIM(RTRIM(PayerName_Raw)), LTRIM(RTRIM(ISNULL(Aging, '(blank)')));    
    
    PRINT 'usp_RefreshNW_CS_InsuranceVsAging completed.';    
END 
go

--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsAging
--AS
--BEGIN
--    SET NOCOUNT ON;

--    TRUNCATE TABLE dbo.NW_CS_InsuranceVsAging;

--    INSERT INTO dbo.NW_CS_InsuranceVsAging
--        (PayerName, AgingBucket, VisitCount, InsuranceBalance, RefreshedAt)
--    SELECT
--        LTRIM(RTRIM(PayerName_Raw))                                  AS PayerName,        -- This lab has no AgingBucket column; bucket label derived from DaystoDOS.
--        CASE
--          WHEN ISNULL(TRY_CAST(DaystoDOS AS INT), -1) < 0   THEN '(blank)'
--          WHEN TRY_CAST(DaystoDOS AS INT) < 30              THEN 'Current'
--          WHEN TRY_CAST(DaystoDOS AS INT) < 60              THEN '30 Days'
--          WHEN TRY_CAST(DaystoDOS AS INT) < 90              THEN '60 Days'
--          WHEN TRY_CAST(DaystoDOS AS INT) < 120             THEN '90 Days'
--          ELSE '120+ Days'
--        END                                                          AS AgingBucket,
--        COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))             AS VisitCount,
--        ISNULL(SUM(TRY_CAST(InsuranceBalance AS DECIMAL(18,2))), 0)  AS InsuranceBalance,
--        GETDATE()
--    FROM dbo.ClaimLevelData
--    WHERE PayerName_Raw IS NOT NULL
--      AND LTRIM(RTRIM(PayerName_Raw)) <> ''
--      AND ISNULL(TRY_CAST(InsuranceBalance AS DECIMAL(18,2)), 0) <> 0
--      AND LTRIM(RTRIM(ClaimStatus)) <> 'No Response'
--    GROUP BY LTRIM(RTRIM(PayerName_Raw)),
--             CASE
--               WHEN ISNULL(TRY_CAST(DaystoDOS AS INT), -1) < 0   THEN '(blank)'
--               WHEN TRY_CAST(DaystoDOS AS INT) < 30              THEN 'Current'
--               WHEN TRY_CAST(DaystoDOS AS INT) < 60              THEN '30 Days'
--               WHEN TRY_CAST(DaystoDOS AS INT) < 90              THEN '60 Days'
--               WHEN TRY_CAST(DaystoDOS AS INT) < 120             THEN '90 Days'
--               ELSE '120+ Days'
--             END;

--    PRINT 'usp_RefreshNW_CS_InsuranceVsAging completed.';
--END
--GO


-- 8. Panel vs Payment  (ClaimLevelData / CheckDate / PanelType + PayerName_Raw / monthly)




CREATE  or Alter PROCEDURE dbo.usp_RefreshNW_CS_PanelVsPayment  
AS  
BEGIN  
    SET NOCOUNT ON;  
  
    TRUNCATE TABLE dbo.NW_CS_PanelVsPayment;  
  
    INSERT INTO dbo.NW_CS_PanelVsPayment  
        (PanelName, PayerName, BillYear, BillMonth, NoOfClaims, InsurancePayment, RefreshedAt)  
    SELECT  
        LTRIM(RTRIM(ISNULL(PanelType,     'Unknown')))              AS PanelName,  
        LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))              AS PayerName,  
        YEAR (TRY_CAST(CheckDate AS DATE))                          AS BillYear,  
        CAST(MONTH(TRY_CAST(CheckDate AS DATE)) AS TINYINT)         AS BillMonth,  
        COUNT(NULLIF(LTRIM(RTRIM(ClaimID)), ''))           AS NoOfClaims,  
        ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0) AS InsurancePayment,  
        GETDATE()  
    FROM dbo.ClaimLevelData  
    WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0  
      --AND PanelType IS NOT NULL AND LTRIM(RTRIM(PanelType)) <> ''  
      AND TRY_CAST(CheckDate AS DATE) IS NOT NULL  
      AND YEAR(TRY_CAST(CheckDate AS DATE)) > 1900  
   AND CheckDate<>''  
    GROUP BY  
        LTRIM(RTRIM(ISNULL(PanelType,     'Unknown'))),  
        LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))),  
        YEAR (TRY_CAST(CheckDate AS DATE)),  
        MONTH(TRY_CAST(CheckDate AS DATE));  
  
    PRINT 'usp_RefreshNW_CS_PanelVsPayment completed.';  
END  
 
Go


--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_PanelVsPayment
--AS
--BEGIN
--    SET NOCOUNT ON;

--    TRUNCATE TABLE dbo.NW_CS_PanelVsPayment;

--    INSERT INTO dbo.NW_CS_PanelVsPayment
--        (PanelName, PayerName, BillYear, BillMonth, NoOfClaims, InsurancePayment, RefreshedAt)
--    SELECT
--        LTRIM(RTRIM(ISNULL(PanelType,     'Unknown')))              AS PanelName,
--        LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))              AS PayerName,
--        YEAR (TRY_CAST(CheckDate AS DATE))                          AS BillYear,
--        CAST(MONTH(TRY_CAST(CheckDate AS DATE)) AS TINYINT)         AS BillMonth,
--        COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))           AS NoOfClaims,
--        ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0) AS InsurancePayment,
--        GETDATE()
--    FROM dbo.ClaimLevelData
--    WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--      AND PanelType IS NOT NULL AND LTRIM(RTRIM(PanelType)) <> ''
--      AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
--      AND YEAR(TRY_CAST(CheckDate AS DATE)) > 1900
--    GROUP BY
--        LTRIM(RTRIM(ISNULL(PanelType,     'Unknown'))),
--        LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))),
--        YEAR (TRY_CAST(CheckDate AS DATE)),
--        MONTH(TRY_CAST(CheckDate AS DATE));

--    PRINT 'usp_RefreshNW_CS_PanelVsPayment completed.';
--END



-- 9. Rep vs Payment


CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_RepVsPayment
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE dbo.NW_CS_RepVsPayment;

    INSERT INTO dbo.NW_CS_RepVsPayment
        (SalesRepName, CheckYear, CheckMonth, NoOfClaims, InsurancePayment, RefreshedAt)
    SELECT
        LTRIM(RTRIM(SalesRepname))                                   AS SalesRepName,
        YEAR (TRY_CAST(CheckDate AS DATE))                           AS CheckYear,
        CAST(MONTH(TRY_CAST(CheckDate AS DATE)) AS TINYINT)          AS CheckMonth,
        COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))            AS NoOfClaims,
        ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0)  AS InsurancePayment,
        GETDATE()
    FROM dbo.ClaimLevelData
    WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
      AND SalesRepname IS NOT NULL AND LTRIM(RTRIM(SalesRepname)) <> ''
      AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
    GROUP BY
        LTRIM(RTRIM(SalesRepname)),
        YEAR (TRY_CAST(CheckDate AS DATE)),
        MONTH(TRY_CAST(CheckDate AS DATE));

    PRINT 'usp_RefreshNW_CS_RepVsPayment completed.';
END
GO


-- 10. Insurance vs Payment %  (Filter: InsurancePayment > 0, Row: PayerName_Raw, Col: NoOfClaimID, InsPayment, Pct)

CREATE or Alter  PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsPaymentPct  
AS  
BEGIN  
    SET NOCOUNT ON;  
  
    ;WITH base AS  
    (  
        SELECT  
            LTRIM(RTRIM(PayerName_Raw)) AS PayerName,  
            LTRIM(RTRIM(Panelname)) AS PanelName,  
  
            TRY_CAST(InsurancePayment AS DECIMAL(18,2)) AS InsPay,  
            TRY_CAST(PaymentPercent AS DECIMAL(9,4)) AS PayPct,  
  
            CheckDateValue =  
                COALESCE(  
                    TRY_CONVERT(DATE, CheckDate, 101),  
                    TRY_CONVERT(DATE, CheckDate, 120),  
                    TRY_CONVERT(DATE, CheckDate)  
                )  
        FROM dbo.ClaimLevelData  
        WHERE ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0    
  --AND TRY_CAST(CheckDate AS DATE) IS NOT NULL and CheckDate<>''  
     -- AND YEAR(TRY_CAST(CheckDate AS DATE)) > 1900  
    ),  
    filtered AS  
    (  
        SELECT  
            PayerName,  
            PanelName,  
            InsPay,  
            PayPct  
        FROM base  
       -- WHERE CheckDateValue <> '2026-04-01'   
    ),  
    agg AS  
    (  
        SELECT  
            PayerName,  
            COUNT(*) AS PanelGroupCount,  
            ISNULL(SUM(InsPay), 0) AS InsurancePayment,  
            ROUND(ISNULL(AVG(PayPct), 0) * 100, 0) AS PaymentPct  
        FROM filtered  
        GROUP BY PayerName  
    ),  
    grand AS  
    (  
        SELECT NULLIF(SUM(InsurancePayment), 0) AS Total  
        FROM agg  
    )  
    SELECT  
        a.PayerName,  
        a.PanelGroupCount,  
        a.InsurancePayment,  
        a.PaymentPct  
    INTO #out  
    FROM agg a  
    CROSS JOIN grand g;  
  
    TRUNCATE TABLE dbo.NW_CS_InsuranceVsPaymentPct;  
  
    INSERT INTO dbo.NW_CS_InsuranceVsPaymentPct  
    (  
        PayerName,  
        NoOfPaidClaims,  
		InsurancePayment,  
        PaymentPct,  
        RefreshedAt  
    )  
    SELECT  
        PayerName,  
        PanelGroupCount,  
        InsurancePayment,  
        PaymentPct,  
        GETDATE()  
    FROM #out  
    ORDER BY InsurancePayment DESC;  
  
    DROP TABLE IF EXISTS #out;  
  
    PRINT 'usp_RefreshNW_CS_InsuranceVsPaymentPct completed.';  
END;  
go

--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsPaymentPct
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH agg AS (
--        SELECT
--            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
--            COUNT(NULLIF(LTRIM(RTRIM(ClaimID)), ''))          AS NoOfPaidClaims,
--            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS InsurancePayment
--        FROM dbo.ClaimLevelData
--        WHERE
--		--PayerName_Raw IS NOT NULL
--        --  AND LTRIM(RTRIM(PayerName_Raw)) <> '' AND
--           ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--        GROUP BY LTRIM(RTRIM(PayerName_Raw))
--    ),
--    grand AS (
--        SELECT NULLIF(SUM(InsurancePayment), 0) AS Total FROM agg
--    )
--    SELECT a.PayerName, a.NoOfPaidClaims, a.InsurancePayment,
--           CAST(a.InsurancePayment * 100.0 / ISNULL(g.Total, 1) AS DECIMAL(9,4)) AS PaymentPct
--    INTO #out
--    FROM agg a CROSS JOIN grand g;

--    TRUNCATE TABLE dbo.NW_CS_InsuranceVsPaymentPct;
--    INSERT INTO dbo.NW_CS_InsuranceVsPaymentPct
--        (PayerName, NoOfPaidClaims, InsurancePayment, PaymentPct, RefreshedAt)
--    SELECT PayerName, NoOfPaidClaims, InsurancePayment, PaymentPct, GETDATE()
--    FROM #out
--    ORDER BY InsurancePayment DESC;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_InsuranceVsPaymentPct completed.';
--END
--GO

--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsPaymentPct
--AS
--BEGIN
--    SET NOCOUNT ON;

--    ;WITH agg AS (
--        SELECT
--            LTRIM(RTRIM(PayerName_Raw))                                AS PayerName,
--            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))          AS NoOfPaidClaims,
--            ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),0) AS InsurancePayment
--        FROM dbo.ClaimLevelData
--        WHERE PayerName_Raw IS NOT NULL
--          AND LTRIM(RTRIM(PayerName_Raw)) <> ''
--          AND ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
--        GROUP BY LTRIM(RTRIM(PayerName_Raw))
--    ),
--    grand AS (
--        SELECT NULLIF(SUM(InsurancePayment), 0) AS Total FROM agg
--    )
--    SELECT a.PayerName, a.NoOfPaidClaims, a.InsurancePayment,
--           CAST(a.InsurancePayment * 100.0 / ISNULL(g.Total, 1) AS DECIMAL(9,4)) AS PaymentPct
--    INTO #out
--    FROM agg a CROSS JOIN grand g;

--    TRUNCATE TABLE dbo.NW_CS_InsuranceVsPaymentPct;
--    INSERT INTO dbo.NW_CS_InsuranceVsPaymentPct
--        (PayerName, NoOfPaidClaims, InsurancePayment, PaymentPct, RefreshedAt)
--    SELECT PayerName, NoOfPaidClaims, InsurancePayment, PaymentPct, GETDATE()
--    FROM #out
--    ORDER BY InsurancePayment DESC;

--    DROP TABLE IF EXISTS #out;
--    PRINT 'usp_RefreshNW_CS_InsuranceVsPaymentPct completed.';
--END
--GO


-- 11. CPT vs Payment %
CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_CptVsPaymentPct
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH agg AS (
        SELECT
            LTRIM(RTRIM(CPTCode))                                      AS CPTCode,
            ISNULL(SUM(TRY_CAST(Units AS DECIMAL(18,2))), 0)           AS SumUnits,
            ISNULL(SUM(CASE WHEN LTRIM(RTRIM(ClaimStatus)) IN ('Fully Paid','Partially Paid')
                            THEN TRY_CAST(InsurancePayment AS DECIMAL(18,2)) ELSE 0 END), 0) AS PaidIns,
            ISNULL(SUM(CASE WHEN LTRIM(RTRIM(ClaimStatus)) IN ('Fully Paid','Partially Paid')
                            THEN TRY_CAST(ChargeAmount     AS DECIMAL(18,2)) ELSE 0 END), 0) AS PaidChg
        FROM dbo.LineLevelData
        WHERE CPTCode IS NOT NULL AND LTRIM(RTRIM(CPTCode)) <> ''
        GROUP BY LTRIM(RTRIM(CPTCode))
    )
    SELECT CPTCode, SumUnits, PaidIns, PaidChg,
           CASE WHEN PaidChg > 0
                THEN CAST(PaidIns * 100.0 / PaidChg AS DECIMAL(9,4))
                ELSE 0 END AS PaymentPct
    INTO #out
    FROM agg;

    TRUNCATE TABLE dbo.NW_CS_CptVsPaymentPct;
    INSERT INTO dbo.NW_CS_CptVsPaymentPct
        (CPTCode, SumUnits, PaidInsurancePayment, PaidChargeAmount, PaymentPct, RefreshedAt)
    SELECT CPTCode, SumUnits, PaidIns, PaidChg, PaymentPct, GETDATE()
    FROM #out
    ORDER BY SumUnits DESC;

    DROP TABLE IF EXISTS #out;
    PRINT 'usp_RefreshNW_CS_CptVsPaymentPct completed.';
END
GO


-- 12. Status Summary


CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_StatusSummary
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE dbo.NW_CS_StatusSummary;

    INSERT INTO dbo.NW_CS_StatusSummary
        (ClaimStatus, PanelName, CptCode, PayerName,
         NoOfClaims, InsurancePayment, InsuranceBalance, PatientBalance, RefreshedAt)
    SELECT
        ISNULL(LTRIM(RTRIM(ClaimStatus)),              '(blank)') AS ClaimStatus,
        ISNULL(LTRIM(RTRIM(PanelType)),                   '(blank)') AS PanelName,
        ISNULL(LTRIM(RTRIM(CPTCodeXUnitsXModifier)),   '(blank)') AS CptCode,
        ISNULL(LTRIM(RTRIM(PayerName_Raw)),            '(blank)') AS PayerName,
        --COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)),'')) AS NoOfClaims,
		 COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)),'')) AS NoOfClaims,
        ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0) AS InsurancePayment,
        ISNULL(SUM(TRY_CAST(InsuranceBalance AS DECIMAL(18,2))), 0) AS InsuranceBalance,
        ISNULL(SUM(TRY_CAST(PatientBalance   AS DECIMAL(18,2))), 0) AS PatientBalance,
        GETDATE()
    FROM dbo.ClaimLevelData
    GROUP BY
        LTRIM(RTRIM(ClaimStatus)),
        LTRIM(RTRIM(PanelType)),
        LTRIM(RTRIM(CPTCodeXUnitsXModifier)),
        LTRIM(RTRIM(PayerName_Raw));

    PRINT 'usp_RefreshNW_CS_StatusSummary completed.';
END
GO


--CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_StatusSummary
--AS
--BEGIN
--    SET NOCOUNT ON;

--    TRUNCATE TABLE dbo.NW_CS_StatusSummary;

--    INSERT INTO dbo.NW_CS_StatusSummary
--        (ClaimStatus, PanelName, CptCode, PayerName,
--         NoOfClaims, InsurancePayment, InsuranceBalance, PatientBalance, RefreshedAt)
--    SELECT
--        ISNULL(LTRIM(RTRIM(ClaimStatus)),              '(blank)') AS ClaimStatus,
--        ISNULL(LTRIM(RTRIM(PanelType)),                   '(blank)') AS PanelName,
--        ISNULL(LTRIM(RTRIM(CPTCodeXUnitsXModifier)),   '(blank)') AS CptCode,
--        ISNULL(LTRIM(RTRIM(PayerName_Raw)),            '(blank)') AS PayerName,
--        COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)),'')) AS NoOfClaims,
--        ISNULL(SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))), 0) AS InsurancePayment,
--        ISNULL(SUM(TRY_CAST(InsuranceBalance AS DECIMAL(18,2))), 0) AS InsuranceBalance,
--        ISNULL(SUM(TRY_CAST(PatientBalance   AS DECIMAL(18,2))), 0) AS PatientBalance,
--        GETDATE()
--    FROM dbo.ClaimLevelData
--    GROUP BY
--        LTRIM(RTRIM(ClaimStatus)),
--        LTRIM(RTRIM(PanelType)),
--        LTRIM(RTRIM(CPTCodeXUnitsXModifier)),
--        LTRIM(RTRIM(PayerName_Raw));

--    PRINT 'usp_RefreshNW_CS_StatusSummary completed.';
--END
--GO


-- 13. Provider Summary
CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_ProviderSummary
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH agg AS (
        SELECT
            LTRIM(RTRIM(ReferringProvider))                              AS ReferringProvider,
            COUNT(DISTINCT NULLIF(LTRIM(RTRIM(ClaimID)), ''))            AS NoOfClaims,
            ISNULL(SUM(TRY_CAST(ProcTotalPayment AS DECIMAL(18,2))), 0)  AS ProcTotalPayment,
            ISNULL(SUM(TRY_CAST(InsuranceBalance AS DECIMAL(18,2))), 0)  AS InsuranceBalance,
            ISNULL(SUM(TRY_CAST(PatientBalance   AS DECIMAL(18,2))), 0)  AS PatientBalance
        FROM dbo.ClaimLevelData
        WHERE ReferringProvider IS NOT NULL
          AND LTRIM(RTRIM(ReferringProvider)) <> ''
        GROUP BY LTRIM(RTRIM(ReferringProvider))
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY NoOfClaims DESC) AS ProviderRank,
        ReferringProvider, NoOfClaims, ProcTotalPayment, InsuranceBalance, PatientBalance
    INTO #out
    FROM agg;

    TRUNCATE TABLE dbo.NW_CS_ProviderSummary;
    INSERT INTO dbo.NW_CS_ProviderSummary
        (ProviderRank, ReferringProvider, NoOfClaims,
         ProcTotalPayment, InsuranceBalance, PatientBalance, RefreshedAt)
    SELECT ProviderRank, ReferringProvider, NoOfClaims,
           ProcTotalPayment, InsuranceBalance, PatientBalance, GETDATE()
    FROM #out
    ORDER BY ProviderRank;

    DROP TABLE IF EXISTS #out;
    PRINT 'usp_RefreshNW_CS_ProviderSummary completed.';
END
GO

PRINT '11_NorthWest_CollectionSummary.sql completed.';
GO



IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NW_CS_InsuranceVsPayment')
CREATE TABLE dbo.NW_CS_InsuranceVsPayment
(
    SummaryId        INT           NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PayerName        NVARCHAR(200) NOT NULL,
    BillYear         SMALLINT      NOT NULL,
    BillMonth        TINYINT       NOT NULL,
    NoOfPaidClaims   INT           NOT NULL DEFAULT 0,
    InsurancePayment DECIMAL(18,2) NOT NULL DEFAULT 0,
    PaymentPct       DECIMAL(9,4)  NOT NULL DEFAULT 0,
    RefreshedAt      DATETIME      NOT NULL DEFAULT GETDATE()
);
go

CREATE OR ALTER PROCEDURE dbo.usp_RefreshNW_CS_InsuranceVsPayment
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH agg AS
    (
        SELECT
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown')))              AS PayerName,

            YEAR (TRY_CAST(CheckDate AS DATE))                          AS BillYear,
            MONTH(TRY_CAST(CheckDate AS DATE))                          AS BillMonth,

            COUNT(NULLIF(LTRIM(RTRIM(ClaimID)), ''))           AS NoOfPaidClaims,

            ISNULL(
                SUM(TRY_CAST(InsurancePayment AS DECIMAL(18,2))),
                0
            )                                                           AS InsurancePayment

        FROM dbo.ClaimLevelData                                          -- ✅ Elix uses LineLevelData
        WHERE
            ISNULL(TRY_CAST(InsurancePayment AS DECIMAL(18,2)), 0) > 0
            --AND CheckDate <> ''
            --AND TRY_CAST(CheckDate AS DATE) IS NOT NULL
            --AND YEAR(TRY_CAST(CheckDate AS DATE)) > 1900

        GROUP BY
            LTRIM(RTRIM(ISNULL(PayerName_Raw, 'Unknown'))),
            YEAR (TRY_CAST(CheckDate AS DATE)),
            MONTH(TRY_CAST(CheckDate AS DATE))
    ),

    grand AS
    (
        SELECT
            BillYear,
            BillMonth,
            NULLIF(SUM(InsurancePayment), 0) AS TotalInsurancePayment
        FROM agg
        GROUP BY
            BillYear,
            BillMonth
    )

    SELECT
        a.PayerName,
        CAST(a.BillYear  AS SMALLINT)  AS BillYear,
        CAST(a.BillMonth AS TINYINT)   AS BillMonth,
        a.NoOfPaidClaims,
        a.InsurancePayment,
        CAST
        (
            a.InsurancePayment * 100.0 /
            ISNULL(g.TotalInsurancePayment, 1)
            AS DECIMAL(9,4)
        )                              AS PaymentPct

    INTO #out
    FROM agg a
    INNER JOIN grand g
        ON  a.BillYear  = g.BillYear
        AND a.BillMonth = g.BillMonth;

    TRUNCATE TABLE dbo.NW_CS_InsuranceVsPayment;

    INSERT INTO dbo.NW_CS_InsuranceVsPayment
    (
        PayerName,
        BillYear,
        BillMonth,
        NoOfPaidClaims,
        InsurancePayment,
        PaymentPct,
        RefreshedAt
    )
    SELECT
        PayerName,
        BillYear,
        BillMonth,
        NoOfPaidClaims,
        InsurancePayment,
        PaymentPct,
        GETDATE()
    FROM #out
    ORDER BY
        BillYear,
        BillMonth,
        InsurancePayment DESC;

    DROP TABLE IF EXISTS #out;

    PRINT 'usp_RefreshNW_CS_InsuranceVsPayment completed.';
END
GO
-- =====================================================================
-- TEST / VERIFICATION  (safe to re-run; no DML, just EXEC + SELECT)
-- Uncomment or run interactively after deploying the file to validate
-- that each SP populates its target table.
-- =====================================================================

/*
EXEC dbo.usp_RefreshNW_CS_Top5ReimbursementPct;
EXEC dbo.usp_RefreshNW_CS_Top5ReimbursementPay;
EXEC dbo.usp_RefreshNW_CS_MonthlyClaimVolume;
EXEC dbo.usp_RefreshNW_CS_WeeklyClaimVolume;
EXEC dbo.usp_RefreshNW_CS_PanelAverages;
EXEC dbo.usp_RefreshNW_CS_AvgPayments;
EXEC dbo.usp_RefreshNW_CS_InsuranceVsAging;
EXEC dbo.usp_RefreshNW_CS_PanelVsPayment;
EXEC dbo.usp_RefreshNW_CS_RepVsPayment;
EXEC dbo.usp_RefreshNW_CS_InsuranceVsPaymentPct;
EXEC dbo.usp_RefreshNW_CS_CptVsPaymentPct;
EXEC dbo.usp_RefreshNW_CS_StatusSummary;
EXEC dbo.usp_RefreshNW_CS_ProviderSummary;

SELECT 'NW_CS_Top5ReimbursementPct'  AS [Table], COUNT(*) AS Rows, MAX(RefreshedAt) AS LastRun FROM dbo.NW_CS_Top5ReimbursementPct
UNION ALL SELECT 'NW_CS_Top5ReimbursementPay',   COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_Top5ReimbursementPay
UNION ALL SELECT 'NW_CS_MonthlyClaimVolume',     COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_MonthlyClaimVolume
UNION ALL SELECT 'NW_CS_WeeklyClaimVolume',      COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_WeeklyClaimVolume
UNION ALL SELECT 'NW_CS_PanelAverages',          COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_PanelAverages
UNION ALL SELECT 'NW_CS_AvgPayments',            COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_AvgPayments
UNION ALL SELECT 'NW_CS_InsuranceVsAging',       COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_InsuranceVsAging
UNION ALL SELECT 'NW_CS_PanelVsPayment',         COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_PanelVsPayment
UNION ALL SELECT 'NW_CS_RepVsPayment',           COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_RepVsPayment
UNION ALL SELECT 'NW_CS_InsuranceVsPaymentPct',  COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_InsuranceVsPaymentPct
UNION ALL SELECT 'NW_CS_CptVsPaymentPct',        COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_CptVsPaymentPct
UNION ALL SELECT 'NW_CS_StatusSummary',          COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_StatusSummary
UNION ALL SELECT 'NW_CS_ProviderSummary',        COUNT(*), MAX(RefreshedAt) FROM dbo.NW_CS_ProviderSummary
ORDER BY [Table];

-- Spot-check the largest tables
SELECT TOP 20 * FROM dbo.NW_CS_PanelAverages          ORDER BY PanelName, PayerName;
SELECT TOP 20 * FROM dbo.NW_CS_MonthlyClaimVolume     ORDER BY PanelName, PayerRank, BillYear, BillMonth;
SELECT TOP 20 * FROM dbo.NW_CS_WeeklyClaimVolume      ORDER BY PanelName, PayerRank, WeekKey;
SELECT *      FROM dbo.NW_CS_Top5ReimbursementPct     ORDER BY PayerRank;
SELECT *      FROM dbo.NW_CS_Top5ReimbursementPay     ORDER BY PayerRank;
*/
