-- ============================================================
-- RisingTides – Executive Summary Refresh SP
-- File : 16_RisingTides_ExecutiveSummary_Aggregate.sql
-- DB   : Rising_Tides
--
-- Run order: AFTER ingestion of ClaimLevelData (and LIS, when available).
-- Called by ClaimLineCSVDataCapture via usp_RefreshRT_ExecutiveSummary.
--
-- Visit Number = ClaimID (per spec).
-- Year / Month bucket  = DateofService.
--
-- LIS BREAKDOWN (RT_ES_LIS, RT_ES_LIS_Panel) – NO LONGER populated here.
--   The LIS breakdown (RoleIDs 'L_A'..'L_N') is now generated by a separate
--   procedure: dbo.usp_RefreshRT_ExecutiveSummary_LIS_Alt
--   (see 19_RisingTides_ExecutiveSummary_LIS_Alt.sql), which is run
--   immediately after this one. This proc only TRUNCATEs RT_ES_LIS and
--   RT_ES_LIS_Panel (clearing the old A-I rows / 'B.<PanelName>' sub-rows
--   from the previous scheme) so the LIS_Alt proc can repopulate RT_ES_LIS
--   with the new L_A..L_N rows and RT_ES_LIS_Panel with the panel-wise
--   'L_B.<PanelName>' sub-rows under "Billable Samples - Resulted".
--
-- PMS BREAKDOWN  (RT_ES_PMS)  – fully populated from dbo.ClaimLevelData
--   O  Billed                          → BilledUnbilled='Billed'
--   P  Billed Mismatches - Non Diagnose US Samples (cross-table vs. dbo.LIMSMaster)
--        = O (Billed - Includes all Claims Billed in AMD, ClaimLevelData, ClaimID-based)
--        - LIMSMaster Billed count (BilledorNot = 'Billed', period by RequestCollectDate)
--        If dbo.LIMSMaster does not exist, the LIMSMaster count is 0 and P = O
--        (guarded by OBJECT_ID('dbo.LIMSMaster','U')).
--   Q  Unbilled - Entered in AMD       → BilledUnbilled='Unbilled'
--   R  Paid - Client                   → ClaimStatus='Client Paid'
--   S  Fully Paid - Insurance Pay      → ClaimStatus='Fully Paid'
--   T  Fully Adjusted                  → ClaimStatus='Complete W/O'
--   U  Patient Responsibility          → ClaimStatus='Patient Responsibility'
--   V  Partially Paid                  → ClaimStatus='Partially Paid'
--   X  Patient Payment                 → ClaimStatus='Patient Payment'
--   W  Insurance Balance               → ClaimStatus IN ('Fully Denied','No Response','Partially Denied')
--   W1 Fully Denied                    → ClaimStatus='Fully Denied'
--   W2 No Response                     → ClaimStatus='No Response'
--   W3 Partially Denied                → ClaimStatus='Partially Denied'
--
-- CASH BREAKDOWN (RT_ES_Cash) – fully populated from dbo.ClaimLevelData
--   X    Total Billed ($)              → SUM(ChargeAmount)        WHERE Billed
--   Y    Unbilled ($)                  → SUM(ChargeAmount)        WHERE Unbilled
--   Z    Insurance Payment fully paid  → SUM(InsurancePayment)    WHERE Billed AND ClaimStatus='Fully Paid'
--   AA   Partially Paid ($)            → SUM(InsurancePayment)    WHERE Billed AND ClaimStatus='Partially Paid'
--   AB   Patient Payment ($)           → SUM(PatientPayment)      WHERE Billed
--   AC   Fully Adjusted (Complete W/O) → SUM(InsuranceAdjustments) WHERE Billed AND ClaimStatus='Complete W/O'
--   AD   Contractual Obligation W/O    → SUM(InsuranceAdjustments) WHERE Billed AND ClaimStatus <> 'Complete W/O'
--   AE   Patient Balance ($)           → SUM(PatientBalance)      WHERE Billed
--   AF   Patient WO ($)                → SUM(PatientAdjustments)  WHERE Billed
--   AG   Insurance Balance ($)         → SUM(InsuranceBalance)    WHERE Billed AND ClaimStatus IN ('Fully Denied','No Response','Partially Denied')
--   AG1  No Response ($)               → SUM(InsuranceBalance)    WHERE Billed AND ClaimStatus='No Response'
--   AG2  Fully Denied ($)              → SUM(InsuranceBalance)    WHERE Billed AND ClaimStatus='Fully Denied'
--   AG3  Partially Denied ($)          → SUM(InsuranceBalance)    WHERE Billed AND ClaimStatus='Partially Denied'
--
-- AVERAGE PAYMENT PER CLAIM (RT_ES_Avg) – fully populated from dbo.ClaimLevelData
--   Numerator (all 3 rows) = SUM(InsurancePayment) WHERE Billed AND ClaimStatus IN ('Fully Paid','Partially Paid')
--                           + SUM(PatientPayment)   WHERE Billed
--                           (i.e. Cash rows Z + AA + AB combined)
--   AH   Average Payment ($) - Total Pay/Billed Claims
--          = Numerator / COUNT(DISTINCT VisitNumber) WHERE Billed
--            (same population as PMS row O)
--   AI1  Average Payment ($) - Total Pay/Paid Claims
--          = Numerator / COUNT(DISTINCT VisitNumber) WHERE Billed
--            AND ClaimStatus IN ('Fully Paid','Partially Paid','Patient Payment')
--            (same population as PMS rows S+V+X)
--   AJ   Average Payment ($) - Total Pay/Adjudicated Claims
--          = Numerator / COUNT(DISTINCT VisitNumber) WHERE Billed
--            AND ClaimStatus IN ('Fully Paid','Complete W/O','Patient Responsibility',
--                                 'Partially Paid','Patient Payment','Fully Denied','Partially Denied')
--            (same population as PMS rows S+T+U+V+X+W1+W3)
--   ESMonthClaimCount stores the denominator used; ESMonthChargeAmount stores the
--   resulting average $ value (0 when the denominator is 0).
--
-- Grand-total sentinel row: ESYear=0, ESMonth=0.
-- ============================================================
SET NOCOUNT ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_RefreshRT_ExecutiveSummary
AS
BEGIN
	SET NOCOUNT ON;

	-- ───────────────────────────────────────────────────────────────────────
	--  Working set – one row per ClaimLevelData row, with normalised values.
	--  Visit Number = ClaimID.
	-- ───────────────────────────────────────────────────────────────────────
	DROP TABLE IF EXISTS #Base;

	SELECT
		LTRIM(RTRIM(ISNULL(ClaimID, '')))                                  AS VisitNumber,
		YEAR (TRY_CAST(DateofService AS DATE))                             AS ESYear,
		MONTH(TRY_CAST(DateofService AS DATE))                             AS ESMonth,
		LTRIM(RTRIM(ISNULL(BilledUnbilled, '')))                           AS BilledUnbilled,
		LTRIM(RTRIM(ISNULL(ClaimStatus,    '')))                           AS ClaimStatus,
		ISNULL(TRY_CAST(ChargeAmount          AS DECIMAL(18,2)), 0)        AS ChargeAmount,
		ISNULL(TRY_CAST(InsurancePayment      AS DECIMAL(18,2)), 0)        AS InsurancePayment,
		ISNULL(TRY_CAST(PatientPayment        AS DECIMAL(18,2)), 0)        AS PatientPayment,
		ISNULL(TRY_CAST(InsuranceAdjustments  AS DECIMAL(18,2)), 0)        AS InsuranceAdjustments,
		ISNULL(TRY_CAST(PatientAdjustments    AS DECIMAL(18,2)), 0)        AS PatientAdjustments,
		ISNULL(TRY_CAST(InsuranceBalance      AS DECIMAL(18,2)), 0)        AS InsuranceBalance,
		ISNULL(TRY_CAST(PatientBalance        AS DECIMAL(18,2)), 0)        AS PatientBalance
	INTO #Base
	FROM dbo.ClaimLevelData
	WHERE TRY_CAST(DateofService AS DATE) IS NOT NULL
	  AND NULLIF(LTRIM(RTRIM(ClaimID)), '') IS NOT NULL;

	-- Periods: every (Year,Month) present in #Base PLUS a (0,0) grand-total sentinel.
	DROP TABLE IF EXISTS #Periods;
	SELECT DISTINCT ESYear, ESMonth INTO #Periods FROM #Base
	UNION ALL SELECT 0, 0;

	-- ───────────────────────────────────────────────────────────────────────
	--  'P' Billed-Mismatch support: pre-aggregate Billed counts.
	--  #BaseBilledCount – ClaimLevelData Billed claims (VisitNumber/ClaimID) per period.
	--  #LisBilled/#LisBilledCount – LIMSMaster rows where BilledorNot='Billed',
	--  per period (empty when dbo.LIMSMaster does not exist, so P degenerates
	--  to P = O).
	--  P = O (Billed - Includes all Claims Billed in AMD, ClaimLevelData)
	--      - LIMSMaster Billed count (BilledorNot = 'Billed').
	-- ───────────────────────────────────────────────────────────────────────
	DROP TABLE IF EXISTS #BaseBilledCount;
	SELECT ESYear, ESMonth, COUNT(DISTINCT VisitNumber) AS BilledCount
	INTO #BaseBilledCount
	FROM #Base
	WHERE BilledUnbilled = 'Billed'
	GROUP BY ESYear, ESMonth
	UNION ALL
	SELECT 0, 0, COUNT(DISTINCT VisitNumber) FROM #Base WHERE BilledUnbilled = 'Billed';

	DROP TABLE IF EXISTS #LisBilled;
	CREATE TABLE #LisBilled
	(
		Accession      NVARCHAR(100) NOT NULL,
		BilledorNot    NVARCHAR(50)  NOT NULL,
		ESYear         INT           NOT NULL,
		ESMonth        INT           NOT NULL
	);

	IF OBJECT_ID('dbo.LIMSMaster','U') IS NOT NULL
	BEGIN
		INSERT INTO #LisBilled (Accession, BilledorNot, ESYear, ESMonth)
		SELECT
			LTRIM(RTRIM(CONVERT(NVARCHAR(100), Accession))),
			LTRIM(RTRIM(ISNULL(BilledorNot, ''))),
			YEAR (TRY_CAST(RequestCollectDate AS DATE)),
			MONTH(TRY_CAST(RequestCollectDate AS DATE))
		FROM dbo.LIMSMaster
		WHERE TRY_CAST(RequestCollectDate AS DATE) IS NOT NULL
		  AND NULLIF(LTRIM(RTRIM(CONVERT(NVARCHAR(100), Accession))), '') IS NOT NULL;
	END

	-- LIMSMaster Billed count: Select BilledorNot from LIMSMaster where BilledorNot='Billed'
	DROP TABLE IF EXISTS #LisBilledCount;
	SELECT ESYear, ESMonth, COUNT(DISTINCT Accession) AS BilledCount
	INTO #LisBilledCount
	FROM #LisBilled
	WHERE BilledorNot = 'Billed'
	GROUP BY ESYear, ESMonth
	UNION ALL
	SELECT 0, 0, COUNT(DISTINCT Accession) FROM #LisBilled WHERE BilledorNot = 'Billed';

	-- ───────────────────────────────────────────────────────────────────────
	--  1.  LIS Breakdown – generation moved to a separate procedure:
	--      dbo.usp_RefreshRT_ExecutiveSummary_LIS_Alt
	--      (19_RisingTides_ExecutiveSummary_LIS_Alt.sql), which is run right
	--      after this one and (re)populates RT_ES_LIS with RoleIDs 'L_A'..'L_N'
	--      and RT_ES_LIS_Panel with the 'L_B.<PanelName>' sub-rows.
	--      Here we just clear out the tables so the old A-I / 'B.<PanelName>'
	--      rows from the previous scheme don't linger.
	-- ───────────────────────────────────────────────────────────────────────
	TRUNCATE TABLE dbo.RT_ES_LIS;
	TRUNCATE TABLE dbo.RT_ES_LIS_Panel;

	-- ───────────────────────────────────────────────────────────────────────
	--  2.  PMS Breakdown
	-- ───────────────────────────────────────────────────────────────────────
	TRUNCATE TABLE dbo.RT_ES_PMS;

	INSERT INTO dbo.RT_ES_PMS (RoleID, Description, ESYear, ESMonth, ESMonthClaimCount, ESMonthChargeAmount, RefreshedAt)
	SELECT RoleID, Description, ESYear, ESMonth, ClaimCount, 0, GETDATE()
	FROM
	(
		-- O  Billed
		SELECT p.ESYear, p.ESMonth, 'O' AS RoleID, 'Billed - Includes all Claims Billed in AMD' AS Description,
			   COUNT(DISTINCT b.VisitNumber) AS ClaimCount
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
		GROUP BY p.ESYear, p.ESMonth

		-- P  Billed Mismatches - Non Diagnose US Samples (degenerates to P = O without LIMSMaster)
		--   = O (Billed - Includes all Claims Billed in AMD, ClaimLevelData)
		--   - LIMSMaster Billed count (BilledorNot = 'Billed')
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'P', 'Billed Mismatches - Non Diagnose US Samples',
			   ISNULL(bb.BilledCount, 0) - ISNULL(ll.BilledCount, 0)
		FROM #Periods p
		LEFT JOIN #BaseBilledCount bb ON bb.ESYear = p.ESYear AND bb.ESMonth = p.ESMonth
		LEFT JOIN #LisBilledCount  ll ON ll.ESYear = p.ESYear AND ll.ESMonth = p.ESMonth

		-- Q  Unbilled - Entered in AMD
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'Q', 'Unbilled - Entered in AMD - Yet to be released to Payer',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Unbilled'
		GROUP BY p.ESYear, p.ESMonth

		-- R  Paid - Client
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'R', 'Paid - Client',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.ClaimStatus='Client Paid'
		GROUP BY p.ESYear, p.ESMonth

		-- S  Fully Paid - Insurance Pay
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'S', 'Fully Paid - Insurance Pay',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Fully Paid'
		GROUP BY p.ESYear, p.ESMonth

		-- T  Fully Adjusted (Complete W/O)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'T', 'Fully Adjusted',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Complete W/O'
		GROUP BY p.ESYear, p.ESMonth

		-- U  Patient Responsibility
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'U', 'Patient Responsibility',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Patient Responsibility'
		GROUP BY p.ESYear, p.ESMonth

		-- V  Partially Paid
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'V', 'Partially Paid',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Partially Paid'
		GROUP BY p.ESYear, p.ESMonth

		-- X  Patient Payment (placed after V so the visual order matches the spec image)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'X', 'Patient Payment',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Patient Payment'
		GROUP BY p.ESYear, p.ESMonth

		-- W  Insurance Balance (parent total = sum of W1+W2+W3)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'W', 'Insurance Balance',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus IN ('Fully Denied','No Response','Partially Denied')
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'W1', '  Fully Denied',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Fully Denied'
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'W2', '  No Response',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='No Response'
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'W3', '  Partially Denied',
			   COUNT(DISTINCT b.VisitNumber)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Partially Denied'
		GROUP BY p.ESYear, p.ESMonth
	) pms;

	-- ───────────────────────────────────────────────────────────────────────
	--  3.  Cash Breakdown
	-- ───────────────────────────────────────────────────────────────────────
	TRUNCATE TABLE dbo.RT_ES_Cash;

	INSERT INTO dbo.RT_ES_Cash (RoleID, Description, ESYear, ESMonth, ESMonthClaimCount, ESMonthChargeAmount, RefreshedAt)
	SELECT RoleID, Description, ESYear, ESMonth, 0, MetricAmount, GETDATE()
	FROM
	(
		-- X  Total Billed ($)
		SELECT p.ESYear, p.ESMonth, 'X' AS RoleID, 'Total Billed ($)' AS Description,
			   ISNULL(SUM(b.ChargeAmount), 0) AS MetricAmount
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
		GROUP BY p.ESYear, p.ESMonth

		-- Y  Unbilled ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'Y', 'Unbilled ($)',
			   ISNULL(SUM(b.ChargeAmount), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Unbilled'
		GROUP BY p.ESYear, p.ESMonth

		-- Z  Insurance Payment (fully paid) ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'Z', 'Insurance Payment (fully paid) ($)',
			   ISNULL(SUM(b.InsurancePayment), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Fully Paid'
		GROUP BY p.ESYear, p.ESMonth

		-- AA  Partially Paid ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AA', 'Partially Paid ($)',
			   ISNULL(SUM(b.InsurancePayment), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Partially Paid'
		GROUP BY p.ESYear, p.ESMonth

		-- AB  Patient Payment ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AB', 'Patient Payment ($)',
			   ISNULL(SUM(b.PatientPayment), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
		GROUP BY p.ESYear, p.ESMonth

		-- AC  Fully Adjusted (Complete W/O) ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AC', 'Fully Adjusted (Complete W/O) ($)',
			   ISNULL(SUM(b.InsuranceAdjustments), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Complete W/O'
		GROUP BY p.ESYear, p.ESMonth

		-- AD  Contractual Obligation W/O  ($)
		--     Sum(InsuranceAdjustments) WHERE Billed AND ClaimStatus <> 'Complete W/O'
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AD', 'Contractual Obligation W/O ($)',
			   ISNULL(SUM(b.InsuranceAdjustments), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus <> 'Complete W/O'
		GROUP BY p.ESYear, p.ESMonth

		-- AE  Patient Balance ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AE', 'Patient Balance ($)',
			   ISNULL(SUM(b.PatientBalance), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
		GROUP BY p.ESYear, p.ESMonth

		-- AF  Patient WO ($)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AF', 'Patient WO ($)',
			   ISNULL(SUM(b.PatientAdjustments), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
		GROUP BY p.ESYear, p.ESMonth

		-- AG  Insurance Balance ($) parent (sum of AG1+AG2+AG3)
		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AG', 'Insurance Balance ($)',
			   ISNULL(SUM(b.InsuranceBalance), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus IN ('Fully Denied','No Response','Partially Denied')
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AG1', '  No Response ($)',
			   ISNULL(SUM(b.InsuranceBalance), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='No Response'
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AG2', '  Fully Denied ($)',
			   ISNULL(SUM(b.InsuranceBalance), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Fully Denied'
		GROUP BY p.ESYear, p.ESMonth

		UNION ALL
		SELECT p.ESYear, p.ESMonth, 'AG3', '  Partially Denied ($)',
			   ISNULL(SUM(b.InsuranceBalance), 0)
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
						  AND b.BilledUnbilled='Billed'
						  AND b.ClaimStatus='Partially Denied'
		GROUP BY p.ESYear, p.ESMonth
	) cash;

	-- ───────────────────────────────────────────────────────────────────────
	--  4.  Average Payment Per Claim (RT_ES_Avg)
	-- ───────────────────────────────────────────────────────────────────────
	TRUNCATE TABLE dbo.RT_ES_Avg;

	;WITH AvgBase AS
	(
		SELECT
			p.ESYear, p.ESMonth,
			ISNULL(SUM(CASE WHEN b.BilledUnbilled='Billed' AND b.ClaimStatus IN ('Fully Paid','Partially Paid')
							THEN b.InsurancePayment ELSE 0 END), 0)
			  + ISNULL(SUM(CASE WHEN b.BilledUnbilled='Billed' THEN b.PatientPayment ELSE 0 END), 0) AS TotalPay,
			COUNT(DISTINCT CASE WHEN b.BilledUnbilled='Billed'
								 THEN b.VisitNumber END) AS BilledClaims,
			COUNT(DISTINCT CASE WHEN b.BilledUnbilled='Billed'
								  AND b.ClaimStatus IN ('Fully Paid','Partially Paid','Patient Payment')
								 THEN b.VisitNumber END) AS PaidClaims,
			COUNT(DISTINCT CASE WHEN b.BilledUnbilled='Billed'
								  AND b.ClaimStatus IN ('Fully Paid','Complete W/O','Patient Responsibility',
														 'Partially Paid','Patient Payment','Fully Denied','Partially Denied')
								 THEN b.VisitNumber END) AS AdjudicatedClaims
		FROM #Periods p
		LEFT JOIN #Base b ON (p.ESYear=0 OR (b.ESYear=p.ESYear AND b.ESMonth=p.ESMonth))
		GROUP BY p.ESYear, p.ESMonth
	)
	INSERT INTO dbo.RT_ES_Avg (RoleID, Description, ESYear, ESMonth, ESMonthClaimCount, ESMonthChargeAmount, RefreshedAt)
	SELECT 'AH', 'Average Payment ($) - Total Pay/Billed Claims', ESYear, ESMonth, BilledClaims,
		   CASE WHEN BilledClaims = 0 THEN 0 ELSE TotalPay / BilledClaims END, GETDATE()
	FROM AvgBase

	UNION ALL
	SELECT 'AI1', 'Average Payment ($) - Total Pay/Paid Claims', ESYear, ESMonth, PaidClaims,
		   CASE WHEN PaidClaims = 0 THEN 0 ELSE TotalPay / PaidClaims END, GETDATE()
	FROM AvgBase

	UNION ALL
	SELECT 'AJ', 'Average Payment ($) - Total Pay/Adjudicated Claims', ESYear, ESMonth, AdjudicatedClaims,
		   CASE WHEN AdjudicatedClaims = 0 THEN 0 ELSE TotalPay / AdjudicatedClaims END, GETDATE()
	FROM AvgBase;

	DROP TABLE IF EXISTS #Base;
	DROP TABLE IF EXISTS #Periods;
	DROP TABLE IF EXISTS #BaseBilledCount;
	DROP TABLE IF EXISTS #LisBilled;
	DROP TABLE IF EXISTS #LisBilledCount;

	PRINT 'usp_RefreshRT_ExecutiveSummary completed.';
END;
GO

PRINT '16_RisingTides_ExecutiveSummary_Aggregate.sql completed.';
GO
