using ClosedXML.Excel;
using LRN.ReportsApi.Models;

namespace LRN.ReportsApi.Services.ArReports;

/// <summary>
/// RPT-01 Excel export.
///
/// Spec section 2.6 requires the export to carry "applied filters, summary totals, detail rows, run
/// ID, generation metadata, and reconciliation totals", and FR-002 requires every summary metric to
/// reconcile to the detail at the same grain. The Reconciliation sheet therefore does not restate
/// the Summary sheet: it RECOMPUTES each measure from the exported detail rows and shows the
/// difference, so a reader can prove the two agree without opening the application.
/// </summary>
internal static class ArActivityReportExcelBuilder
{
    private static readonly XLColor HeaderFill = XLColor.FromHtml("#16325C");
    private static readonly XLColor HeaderText = XLColor.FromHtml("#FFFFFF");
    private static readonly XLColor SectionFill = XLColor.FromHtml("#E9F1FD");
    private static readonly XLColor WarnFill = XLColor.FromHtml("#FDF4E3");

    public static byte[] Build(ArActivityReportResult report)
    {
        using var workbook = new XLWorkbook();
        WriteReportInfo(workbook, report);
        WriteSummary(workbook, report);
        if (report.Groups.Count > 0) WriteGroups(workbook, report);
        WriteDetail(workbook, report);
        WriteReconciliation(workbook, report);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    // ------------------------------------------------------------------------------------
    // Sheet 1 - report run metadata + applied filters (FR-001)
    // ------------------------------------------------------------------------------------
    private static void WriteReportInfo(XLWorkbook workbook, ArActivityReportResult report)
    {
        var sheet = workbook.Worksheets.Add("Report Info");
        var m = report.Metadata;
        var row = 1;

        sheet.Cell(row, 1).Value = $"{m.ReportCode} - {m.ReportName}";
        sheet.Cell(row, 1).Style.Font.SetBold().Font.SetFontSize(15);
        sheet.Range(row, 1, row, 2).Merge();
        row += 2;

        row = Section(sheet, row, "Report run");
        row = Pair(sheet, row, "Report run ID", m.RunId);
        row = Pair(sheet, row, "Lab / client", $"{m.LabName} (LabId {m.LabId})");
        row = Pair(sheet, row, "Generated by", string.IsNullOrWhiteSpace(m.GeneratedBy) ? "-" : m.GeneratedBy);
        row = Pair(sheet, row, "Role", string.IsNullOrWhiteSpace(m.GeneratedByRole) ? "-" : m.GeneratedByRole);
        row = Pair(sheet, row, "Generated on (UTC)", m.GeneratedOn.ToString("dd MMM yyyy HH:mm:ss"));
        row = Pair(sheet, row, "As-of date/time", m.AsOf.ToString("dd MMM yyyy HH:mm"));
        row = Pair(sheet, row, "Data refreshed on", m.DataRefreshedOn?.ToString("dd MMM yyyy HH:mm") ?? "Not available");
        row = Pair(sheet, row, "Data refresh run ID", string.IsNullOrWhiteSpace(m.DataRefreshRunId) ? "Not available" : m.DataRefreshRunId);
        row = Pair(sheet, row, "Report grain", m.Grain);
        row = Pair(sheet, row, "Role view", m.RoleView);
        row = Pair(sheet, row, "Internal notes included", m.InternalNotesVisible ? "Yes" : "No - restricted content is masked in this export");
        row++;

        row = Section(sheet, row, "Applied filters");
        foreach (var filter in m.AppliedFilters)
            row = Pair(sheet, row, filter.Label, filter.Value);
        row++;

        row = Section(sheet, row, "Data availability notes (FR-011)");
        foreach (var note in m.UnavailableMeasures)
        {
            sheet.Cell(row, 1).Value = note;
            sheet.Range(row, 1, row, 2).Merge();
            sheet.Cell(row, 1).Style.Alignment.SetWrapText().Fill.SetBackgroundColor(WarnFill);
            sheet.Row(row).Height = 28;
            row++;
        }

        if (!string.IsNullOrWhiteSpace(report.EmptyStateReason))
        {
            row++;
            row = Section(sheet, row, "Empty state");
            sheet.Cell(row, 1).Value = report.EmptyStateReason;
            sheet.Range(row, 1, row, 2).Merge();
            sheet.Cell(row, 1).Style.Alignment.SetWrapText();
        }

        sheet.Column(1).Width = 34;
        sheet.Column(2).Width = 78;
        sheet.SheetView.FreezeRows(1);
    }

    // ------------------------------------------------------------------------------------
    // Sheet 2 - summary measures (spec section 3.1)
    // ------------------------------------------------------------------------------------
    private static void WriteSummary(XLWorkbook workbook, ArActivityReportResult report)
    {
        var sheet = workbook.Worksheets.Add("Summary");
        var s = report.Summary;

        sheet.Cell(1, 1).Value = "Measure";
        sheet.Cell(1, 2).Value = "Value";
        sheet.Cell(1, 3).Value = "Grain / definition";
        StyleHeader(sheet, 1, 3);

        var rows = new (string Measure, object Value, string Definition)[]
        {
            ("Activity events", s.ActivityEvents, "Activity event count - COUNT(activity_event_id) after filters"),
            ("Distinct claim-days worked", s.DistinctClaimDaysWorked, "Claim count - DISTINCT (claim, analyst, activity date)"),
            ("Distinct line-days worked", s.DistinctLineDaysWorked, "Denial-line count - DISTINCT (line item, analyst, activity date)"),
            ("Distinct claims worked (period)", s.DistinctClaimsWorked, "Claim count - distinct claims touched in the whole period"),
            ("Distinct denial lines worked (period)", s.DistinctLinesWorked, "Denial-line count - distinct lines touched in the whole period"),
            ("Distinct analysts", s.DistinctAnalysts, "Analyst count - distinct activity authors"),
            ("Actions completed", s.ActionsCompleted, "Action count - distinct claim/line with a completed action"),
            ("  of which event-backed", s.ActionsCompletedFromEvents, "Action count - backed by dbo.DenialActionCompletionEvent"),
            ("Escalations raised", s.EscalationsRaised, "Escalation-cycle count - a response is a separate event"),
            ("Notes recorded", s.NotesRecorded, "Activity event count - work notes only"),
            ("Status changes", s.StatusChanges, "Activity event count - status updates only"),
            ("Outstanding balance worked", s.BalanceWorked, "Currency - one balance per claim/analyst/activity date")
        };

        var row = 2;
        foreach (var (measure, value, definition) in rows)
        {
            sheet.Cell(row, 1).Value = measure;
            switch (value)
            {
                case decimal money:
                    sheet.Cell(row, 2).Value = money;
                    sheet.Cell(row, 2).Style.NumberFormat.Format = "$#,##0.00";
                    break;
                default:
                    sheet.Cell(row, 2).Value = Convert.ToInt32(value);
                    sheet.Cell(row, 2).Style.NumberFormat.Format = "#,##0";
                    break;
            }
            sheet.Cell(row, 3).Value = definition;
            row++;
        }

        row++;
        sheet.Cell(row, 1).Value = "Grain labels are not interchangeable (spec section 2.6): claim counts, denial-line counts, activity-event counts and action counts each measure a different thing and must never be added together.";
        sheet.Range(row, 1, row, 3).Merge();
        sheet.Cell(row, 1).Style.Alignment.SetWrapText().Fill.SetBackgroundColor(SectionFill);
        sheet.Row(row).Height = 30;

        if (s.RowsWithFallbackBalance > 0)
        {
            row++;
            sheet.Cell(row, 1).Value = $"{s.RowsWithFallbackBalance:N0} of {s.ActivityEvents:N0} exported rows carry the CURRENT outstanding balance rather than a per-event snapshot, because they predate snapshot capture. Those rows are marked \"Current (not snapshot)\" in the detail sheet.";
            sheet.Range(row, 1, row, 3).Merge();
            sheet.Cell(row, 1).Style.Alignment.SetWrapText().Fill.SetBackgroundColor(WarnFill);
            sheet.Row(row).Height = 30;
        }

        sheet.Column(1).Width = 34;
        sheet.Column(2).Width = 18;
        sheet.Column(3).Width = 66;
        sheet.SheetView.FreezeRows(1);
    }

    // ------------------------------------------------------------------------------------
    // Sheet 3 - the selected grouping
    // ------------------------------------------------------------------------------------
    private static void WriteGroups(XLWorkbook workbook, ArActivityReportResult report)
    {
        var sheet = workbook.Worksheets.Add("Grouped Summary");
        string[] headers =
        [
            "Group", "Activity events", "Distinct claim-days", "Distinct line-days",
            "Distinct claims", "Actions completed", "Escalations raised", "Balance worked"
        ];
        for (var i = 0; i < headers.Length; i++) sheet.Cell(1, i + 1).Value = headers[i];
        StyleHeader(sheet, 1, headers.Length);

        var row = 2;
        foreach (var group in report.Groups)
        {
            sheet.Cell(row, 1).Value = group.GroupLabel;
            sheet.Cell(row, 2).Value = group.ActivityEvents;
            sheet.Cell(row, 3).Value = group.DistinctClaimDaysWorked;
            sheet.Cell(row, 4).Value = group.DistinctLineDaysWorked;
            sheet.Cell(row, 5).Value = group.DistinctClaims;
            sheet.Cell(row, 6).Value = group.ActionsCompleted;
            sheet.Cell(row, 7).Value = group.EscalationsRaised;
            sheet.Cell(row, 8).Value = group.BalanceWorked;
            sheet.Cell(row, 8).Style.NumberFormat.Format = "$#,##0.00";
            row++;
        }

        sheet.Column(1).Width = 34;
        for (var i = 2; i <= headers.Length; i++) sheet.Column(i).Width = 19;
        sheet.SheetView.FreezeRows(1);
    }

    // ------------------------------------------------------------------------------------
    // Sheet 4 - detail rows, in the spec's column-group order
    // ------------------------------------------------------------------------------------
    private static readonly string[] DetailHeaders =
    [
        // Identification
        "Activity ID", "Event Source", "Claim ID", "Line Item ID", "Encounter / Accession", "CPT", "DOS",
        // Classification
        "Payer", "Denial Code", "Denial Classification", "Denial Reason", "Workflow Status",
        "Reporting Bucket", "AR Aging Bucket", "Priority",
        // Assignment
        "AR Analyst", "AR Manager", "Team", "Assigned Date/Time", "Assigned By",
        // Activity
        "Activity Date/Time", "Activity Author", "Activity Type", "Contact Method", "Note Text",
        // Workflow change
        "Previous Status", "New Status", "Status Reason",
        // Action
        "Action Category", "Task", "Action Completed", "Action Completed Date/Time",
        "Action Completed By", "Completion Date Label", "Completion Source",
        // Follow-up
        "Next Follow-up Date", "Follow-up Category", "Original Due Date", "Reschedule Count", "Due Status (as-of)",
        // Escalation
        "Escalated", "Escalation ID", "Escalation Reason", "Escalation Recipient", "Escalation Status",
        // Financial
        "Original Charge", "Outstanding Balance", "Balance Basis",
        // Audit
        "Update Source", "Upload Batch / Run ID", "Source Run ID", "Created By"
    ];

    private static void WriteDetail(XLWorkbook workbook, ArActivityReportResult report)
    {
        var sheet = workbook.Worksheets.Add("Activity Detail");
        for (var i = 0; i < DetailHeaders.Length; i++) sheet.Cell(1, i + 1).Value = DetailHeaders[i];
        StyleHeader(sheet, 1, DetailHeaders.Length);

        var row = 2;
        foreach (var r in report.Detail.Items)
        {
            var col = 1;
            void Text(string? value) => sheet.Cell(row, col++).Value = value ?? string.Empty;
            void Date(DateTime? value, string format)
            {
                var cell = sheet.Cell(row, col++);
                // Typed dates, not strings (FR-005): a reader must be able to sort and filter these.
                if (value.HasValue) { cell.Value = value.Value; cell.Style.DateFormat.Format = format; }
                else cell.Value = string.Empty;
            }
            void Money(decimal value)
            {
                var cell = sheet.Cell(row, col++);
                cell.Value = value;
                cell.Style.NumberFormat.Format = "$#,##0.00";
            }
            void Number(int value)
            {
                var cell = sheet.Cell(row, col++);
                cell.Value = value;
                cell.Style.NumberFormat.Format = "#,##0";
            }

            Text(r.ActivityId);
            Text(r.SourceType);
            Text(r.ClaimId);
            Text(r.LineItemId);
            Text(r.EncounterNumber);
            Text(r.CptCode);
            Date(r.DateOfService, "dd-MMM-yyyy");

            Text(r.PayerName);
            Text(r.DenialCode);
            Text(r.DenialClassification);
            Text(r.DenialReason);
            Text(r.WorkflowStatus);
            Text(r.ReportingBucket);
            Text(r.AgingBucket);
            Text(r.Priority);

            Text(r.AnalystName);
            Text(string.IsNullOrWhiteSpace(r.ManagerName) ? "Not on file" : r.ManagerName);
            Text(string.IsNullOrWhiteSpace(r.TeamName) ? "Not on file" : r.TeamName);
            Date(r.AssignedOn, "dd-MMM-yyyy HH:mm");
            Text(r.AssignedBy);

            Date(r.ActivityDate, "dd-MMM-yyyy HH:mm");
            Text(r.Author);
            Text(r.ActivityType);
            Text(r.ContactMethod);
            Text(r.NoteText);

            // Previous/new status are only factual on a status-change event; on any other event
            // they stay blank rather than being back-filled from current state (spec section 4).
            Text(r.PreviousStatus);
            Text(r.NewStatus);
            Text(r.StatusReason);

            Text(r.ActionCategory);
            Text(r.Task);
            Text(r.ActionCompleted ? "Yes" : "No");
            Date(r.ActionCompletedOn, "dd-MMM-yyyy HH:mm");
            Text(r.ActionCompletedBy);
            Text(r.ActionCompletedDateLabel);
            Text(r.ActionCompleted ? (r.ActionCompletionIsEvent ? "Completion event" : "Task-board flag (current state)") : string.Empty);

            Date(r.NextFollowUpDate, "dd-MMM-yyyy");
            Text(r.FollowUpCategory);
            Date(r.OriginalFollowUpDate, "dd-MMM-yyyy");
            Number(r.RescheduleCount);
            Text(r.DueStatus);

            Text(r.Escalated ? "Yes" : "No");
            Text(r.EscalationId);
            Text(r.EscalationReason);
            Text(r.EscalationRecipient);
            Text(r.EscalationStatus);

            Money(r.OriginalCharge);
            Money(r.BalanceSnapshot);
            Text(r.BalanceIsSnapshot ? "Snapshot at activity" : "Current (not snapshot)");

            Text(r.UpdateSource);
            Text(r.UploadBatchId);
            Text(r.RunId);
            Text(r.CreatedBy);

            row++;
        }

        if (report.Detail.Items.Count > 0)
        {
            sheet.Range(1, 1, row - 1, DetailHeaders.Length).SetAutoFilter();
            foreach (var i in new[] { 1, 3, 4, 5, 6, 8, 10, 16, 21, 23, 25 }) sheet.Column(i).Width = 22;
            sheet.Column(25).Width = 60;   // Note Text
            sheet.Column(25).Style.Alignment.SetWrapText();
        }
        // Sticky identifiers on a wide table (NFR-007): the first six identification columns stay
        // in view while the reader scrolls right through 50+ columns.
        sheet.SheetView.Freeze(1, 6);
    }

    // ------------------------------------------------------------------------------------
    // Sheet 5 - reconciliation (FR-002)
    // ------------------------------------------------------------------------------------
    private static void WriteReconciliation(XLWorkbook workbook, ArActivityReportResult report)
    {
        var sheet = workbook.Worksheets.Add("Reconciliation");
        var rows = report.Detail.Items;
        var s = report.Summary;

        // Recomputed from the exported rows, independently of the SQL aggregates on the Summary
        // sheet. If a difference is ever non-zero, the summary and the detail disagree and the
        // export should not be trusted - which is exactly what this sheet exists to reveal.
        var detailEvents = rows.Count;
        var detailClaimDays = rows.Select(r => $"{r.ClaimId}|{r.Author}|{r.ActivityDateKey}").Distinct(StringComparer.OrdinalIgnoreCase).Count();
        var detailLineDays = rows.Select(r => $"{r.ClaimId}|{r.LineItemId}|{r.Author}|{r.ActivityDateKey}").Distinct(StringComparer.OrdinalIgnoreCase).Count();
        var detailClaims = rows.Select(r => r.ClaimId).Distinct(StringComparer.OrdinalIgnoreCase).Count();
        var detailEscalations = rows.Count(r => r.Escalated);
        var detailActions = rows.Where(r => r.ActionCompleted).Select(r => $"{r.ClaimId}|{r.LineItemId}").Distinct(StringComparer.OrdinalIgnoreCase).Count();
        var detailBalance = rows
            .GroupBy(r => $"{r.ClaimId}|{r.Author}|{r.ActivityDateKey}", StringComparer.OrdinalIgnoreCase)
            .Sum(g => g.Max(r => r.BalanceSnapshot));

        sheet.Cell(1, 1).Value = "Measure";
        sheet.Cell(1, 2).Value = "Summary sheet";
        sheet.Cell(1, 3).Value = "Recomputed from detail rows";
        sheet.Cell(1, 4).Value = "Difference";
        StyleHeader(sheet, 1, 4);

        var row = 2;
        void Line(string label, decimal summary, decimal detail, bool money = false)
        {
            sheet.Cell(row, 1).Value = label;
            sheet.Cell(row, 2).Value = summary;
            sheet.Cell(row, 3).Value = detail;
            sheet.Cell(row, 4).Value = summary - detail;
            var format = money ? "$#,##0.00" : "#,##0";
            for (var c = 2; c <= 4; c++) sheet.Cell(row, c).Style.NumberFormat.Format = format;
            if (summary != detail) sheet.Range(row, 1, row, 4).Style.Fill.SetBackgroundColor(WarnFill);
            row++;
        }

        Line("Activity events", s.ActivityEvents, detailEvents);
        Line("Distinct claim-days worked", s.DistinctClaimDaysWorked, detailClaimDays);
        Line("Distinct line-days worked", s.DistinctLineDaysWorked, detailLineDays);
        Line("Distinct claims worked", s.DistinctClaimsWorked, detailClaims);
        Line("Actions completed", s.ActionsCompleted, detailActions);
        Line("Escalations raised", s.EscalationsRaised, detailEscalations);
        Line("Outstanding balance worked", s.BalanceWorked, detailBalance, money: true);

        row++;
        sheet.Cell(row, 1).Value = report.Detail.TotalCount > rows.Count
            ? $"PARTIAL EXPORT: {rows.Count:N0} of {report.Detail.TotalCount:N0} matching rows were written (export ceiling reached). The summary figures cover ALL matching rows, so differences above are expected. Narrow the filters and export again for a reconciling extract."
            : "All matching rows were exported. Every difference above should be zero; a non-zero difference means the summary and the detail disagree and must be investigated before the numbers are used.";
        sheet.Range(row, 1, row, 4).Merge();
        sheet.Cell(row, 1).Style.Alignment.SetWrapText()
            .Fill.SetBackgroundColor(report.Detail.TotalCount > rows.Count ? WarnFill : SectionFill);
        sheet.Row(row).Height = 34;

        row += 2;
        sheet.Cell(row, 1).Value = "Report run ID";
        sheet.Cell(row, 2).Value = report.Metadata.RunId;
        sheet.Cell(row, 1).Style.Font.SetBold();
        row++;
        sheet.Cell(row, 1).Value = "Generated on (UTC)";
        sheet.Cell(row, 2).Value = report.Metadata.GeneratedOn.ToString("dd MMM yyyy HH:mm:ss");
        sheet.Cell(row, 1).Style.Font.SetBold();

        sheet.Column(1).Width = 34;
        for (var c = 2; c <= 4; c++) sheet.Column(c).Width = 26;
        sheet.SheetView.FreezeRows(1);
    }

    // ------------------------------------------------------------------------------------

    private static void StyleHeader(IXLWorksheet sheet, int row, int lastColumn)
    {
        var range = sheet.Range(row, 1, row, lastColumn);
        range.Style.Font.SetBold().Font.SetFontColor(HeaderText);
        range.Style.Fill.SetBackgroundColor(HeaderFill);
        range.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Center).Alignment.SetWrapText();
        sheet.Row(row).Height = 30;
    }

    private static int Section(IXLWorksheet sheet, int row, string title)
    {
        sheet.Cell(row, 1).Value = title;
        sheet.Range(row, 1, row, 2).Merge();
        sheet.Cell(row, 1).Style.Font.SetBold().Fill.SetBackgroundColor(SectionFill);
        return row + 1;
    }

    private static int Pair(IXLWorksheet sheet, int row, string label, string value)
    {
        sheet.Cell(row, 1).Value = label;
        sheet.Cell(row, 1).Style.Font.SetBold();
        sheet.Cell(row, 2).Value = value;
        sheet.Cell(row, 2).Style.Alignment.SetWrapText();
        return row + 1;
    }
}
