namespace LabMetricsDashboard.Models;

/// <summary>
/// Single source of truth for the Payer Policy Validation column set —
/// used by both the results grid (Index.cshtml) and the Excel export so
/// they always stay in sync with dbo.PayerValidationReport.
/// </summary>
public static class PayerPolicyValidationColumns
{
    /// <summary>One grid/export column: header text, value selector, money flag.</summary>
    public sealed record Column(string Header, Func<PredictionRecord, object?> Value, bool IsMoney = false);

    public static readonly IReadOnlyList<Column> All =
    [
        new("RunId",                                r => r.RunId),
        new("WeekFolder",                           r => r.WeekFolder),
        new("AccessionNo",                          r => r.AccessionNo),
        new("VisitNumber",                          r => r.VisitNumber),
        new("CPTCode",                              r => r.CPTCode),
        new("PatientDOB",                           r => r.PatientDOB),
        new("PayerCode",                            r => r.PayerCode),
        new("PayerName",                            r => r.PayerName),
        new("PayerNameNormalized",                  r => r.PayerNameNormalized),
        new("PayStatus",                            r => r.PayStatus),
        new("HistoricalPayment",                    r => r.HistoricalPayment),
        new("HistoricalPaidLineItemCount",          r => r.HistoricalPaidLineItemCount),
        new("HistoricalPaymentConfidenceScore",     r => r.HistoricalPaymentConfidenceScore),
        new("TotalLineItemCount",                   r => r.TotalLineItemCount),
        new("PaidLineItemCount",                    r => r.PaidLineItemCount),
        new("PctPaidLineItemCount",                 r => r.PctPaidLineItemCount),
        new("PayerType",                            r => r.PayerType),
        new("PayerFoundInPolicy",                   r => r.PayerFoundInPolicy),
        new("DateOfService",                        r => r.DateOfService),
        new("FirstBilledDate",                      r => r.FirstBilledDate),
        new("PanelName",                            r => r.PanelName),
        new("LISIcd10Codes",                        r => r.LISIcd10Codes),
        new("CCWIcd10Code",                         r => r.CCWIcd10Code),
        new("Units",                                r => r.Units),
        new("Modifier",                             r => r.Modifier),
        new("DenialCode",                           r => r.DenialCode),
        new("DenialDescription",                    r => r.DenialDescription),
        new("BilledAmount",                         r => r.BilledAmount, IsMoney: true),
        new("AllowedAmount",                        r => r.AllowedAmount, IsMoney: true),
        new("InsurancePayment",                     r => r.InsurancePayment, IsMoney: true),
        new("InsuranceAdjustment",                  r => r.InsuranceAdjustment, IsMoney: true),
        new("PatientPaidAmount",                    r => r.PatientPaidAmount, IsMoney: true),
        new("PatientAdjustment",                    r => r.PatientAdjustment, IsMoney: true),
        new("InsuranceBalance",                     r => r.InsuranceBalance, IsMoney: true),
        new("PatientBalance",                       r => r.PatientBalance, IsMoney: true),
        new("TotalBalance",                         r => r.TotalBalance, IsMoney: true),
        new("MedicareFee",                          r => r.MedicareFee, IsMoney: true),
        new("FinalClaimStatus",                     r => r.FinalClaimStatus),
        new("CoveredIcd10CodesBilled",              r => r.CoveredIcd10CodesBilled),
        new("NonCoveredIcd10CodesBilled",           r => r.NonCoveredIcd10CodesBilled),
        new("BilledIcdCodesNotAvailableInPolicy",   r => r.BilledIcdCodesNotAvailableInPayerPolicy),
        new("CoverageStatus",                       r => r.CoverageStatus),
        new("FinalCoverageStatus",                  r => r.FinalCoverageStatus),
        new("CoveredIcd10CodesAsPerPayerPolicy",    r => r.CoveredIcd10CodesAsPerPayerPolicy),
        new("NonCoveredIcd10CodesAsPerPayerPolicy", r => r.NonCoveredIcd10CodesAsPerPayerPolicy),
        new("ActionComment",                        r => r.ActionComment),
        new("Resolution",                           r => r.Resolution),
        new("CodingValidation",                     r => r.CodingValidation),
        new("CodingValidationSubStatus",            r => r.CodingValidationSubStatus),
        new("ICDComplianceStatus",                  r => r.ICDComplianceStatus),
        new("ICDComplianceSubstatus",               r => r.ICDComplianceSubstatus),
        new("ICDPrimaryIndicatorAvailable",         r => r.ICDPrimaryIndicatorAvailable),
        new("CoveredICDPresence",                   r => r.CoveredICDPresence),
        new("ICDValidationConfidence",              r => r.ICDValidationConfidence),
        new("FrequencyConditionMet",                r => r.FrequencyConditionMet),
        new("GenderConditionMet",                   r => r.GenderConditionMet),
        new("Payability",                           r => r.Payability),
        new("ForecastingPayability",                r => r.ForecastingPayability),
        new("PolicyCoverageExpectation",            r => r.PolicyCoverageExpectation),
        new("DenialValidity",                       r => r.DenialValidity),
        new("CoverageExpectationRemarks",           r => r.CoverageExpectationRemarks),
        new("ExpectedAverageAllowedAmount",         r => r.ExpectedAverageAllowedAmount, IsMoney: true),
        new("ExpectedAverageInsurancePayment",      r => r.ExpectedAverageInsurancePayment, IsMoney: true),
        new("ExpectedAllowedAmountSameLab",         r => r.ExpectedAllowedAmountSameLab, IsMoney: true),
        new("ExpectedInsurancePaymentSameLab",      r => r.ExpectedInsurancePaymentSameLab, IsMoney: true),
        new("ModeAllowedAmountSameLab",             r => r.ModeAllowedAmountSameLab, IsMoney: true),
        new("ModeInsurancePaidSameLab",             r => r.ModeInsurancePaidSameLab, IsMoney: true),
        new("ModeAllowedAmountPeer",                r => r.ModeAllowedAmountPeer, IsMoney: true),
        new("ModeInsurancePaidPeer",                r => r.ModeInsurancePaidPeer, IsMoney: true),
        new("MedianAllowedAmountSameLab",           r => r.MedianAllowedAmountSameLab, IsMoney: true),
        new("MedianInsurancePaidSameLab",           r => r.MedianInsurancePaidSameLab, IsMoney: true),
        new("MedianAllowedAmountPeer",              r => r.MedianAllowedAmountPeer, IsMoney: true),
        new("MedianInsurancePaidPeer",              r => r.MedianInsurancePaidPeer, IsMoney: true),
        new("ModeAllowedAmountDifference",          r => r.ModeAllowedAmountDifference, IsMoney: true),
        new("ModeInsurancePaidDifference",          r => r.ModeInsurancePaidDifference, IsMoney: true),
        new("MedianAllowedAmountDifference",        r => r.MedianAllowedAmountDifference, IsMoney: true),
        new("MedianInsurancePaidDifference",        r => r.MedianInsurancePaidDifference, IsMoney: true),
        new("DenialRate",                           r => r.DenialRate),
        new("AdjustmentRate",                       r => r.AdjustmentRate),
        new("PaymentDays",                          r => r.PaymentDays),
        new("ExpectedPaymentDate",                  r => r.ExpectedPaymentDate),
        new("ExpectedPaymentMonth",                 r => r.ExpectedPaymentMonth),
        new("BillingProvider",                      r => r.BillingProvider),
        new("ReferringProvider",                    r => r.ReferringProvider),
        new("ClinicName",                           r => r.ClinicName),
        new("SalesRepName",                         r => r.SalesRepName),
        new("PatientID",                            r => r.PatientID),
        new("ChargeEnteredDate",                    r => r.ChargeEnteredDate),
        new("POS",                                  r => r.POS),
        new("TOS",                                  r => r.TOS),
        new("CheckDate",                            r => r.CheckDate),
        new("DaysToDOS",                            r => r.DaysToDOS),
        new("RollingDays",                          r => r.RollingDays),
        new("DaysToBill",                           r => r.DaysToBill),
        new("DaysToPost",                           r => r.DaysToPost),
        new("InsertedDateTime",                     r => r.InsertedDateTime),
        new("ForecastingPayabilitySubstatus",       r => r.ForecastingPayabilitySubstatus),
        new("PredictionStatus",                     r => r.PredictionStatus),
        new("Variance_AllowedAmount",               r => r.Variance_AllowedAmount, IsMoney: true),
        new("Variance_PaidAmount",                  r => r.Variance_PaidAmount, IsMoney: true),
    ];
}
